package drai.dev.gravelmon.pokemon.attributes;

import com.google.gson.*;
import drai.dev.data.jsonwriters.*;
import org.jetbrains.annotations.*;

import java.util.*;

public enum Ability {
    ADAPTABILITY(true, null, "pokemon"),
    AERILATE(true, null, "pokemon"),
    AFTERMATH(true, null, "pokemon"),
    AIR_LOCK(true, null, "pokemon"),
    ANALYTIC(true, null, "pokemon"),
    ANGER_POINT(true, null, "pokemon"),
    ANGER_SHELL(true, null, "pokemon"),
    ANTICIPATION(true, null, "pokemon"),
    ARENA_TRAP(true, null, "pokemon"),
    ARMOR_TAIL(true, null, "pokemon"),
    AROMA_VEIL(true, null, "pokemon"),
    AS_ONE(true, null, "pokemon"),
    AURA_BREAK(true, null, "pokemon"),
    BAD_DREAMS(true, null, "pokemon"),
    BALL_FETCH(true, null, "pokemon"),
    BATTERY(true, null, "pokemon"),
    BATTLE_ARMOR(true, null, "pokemon"),
    BATTLE_BOND(true, null, "pokemon"),
    BEADS_OF_RUIN(true, null, "pokemon"),
    BEAST_BOOST(true, null, "pokemon"),
    BERSERK(true, null, "pokemon"),
    BIG_PECKS(true, null, "pokemon"),
    BLAZE(true, null, "pokemon"),
    BULLETPROOF(true, null, "pokemon"),
    CACOPHONY(false, null, null),
    CHEEK_POUCH(true, null, "pokemon"),
    CHILLING_NEIGH(true, null, "pokemon"),
    CHLOROPHYLL(true, null, "pokemon"),
    CLEAR_BODY(true, null, "pokemon"),
    CLOUD_NINE(true, null, "pokemon"),
    COLOR_CHANGE(true, null, "pokemon"),
    COMATOSE(true, null, "pokemon"),
    COMMANDER(true, null, "pokemon"),
    COMPETITIVE(true, null, "pokemon"),
    COMPOUND_EYES(true, null, "pokemon"),
    CONTRARY(true, null, "pokemon"),
    CORROSION(true, null, "pokemon"),
    COSTAR(true, null, "pokemon"),
    COTTON_DOWN(true, null, "pokemon"),
    CUD_CHEW(true, null, "pokemon"),
    CURIOUS_MEDICINE(true, null, "pokemon"),
    CURSED_BODY(true, null, "pokemon"),
    CUTE_CHARM(true, null, "pokemon"),
    DAMP(true, null, "pokemon"),
    DANCER(true, null, "pokemon"),
    DARK_AURA(true, null, "pokemon"),
    DAUNTLESS_SHIELD(true, null, "pokemon"),
    DAZZLING(true, null, "pokemon"),
    DEFEATIST(true, null, "pokemon"),
    DEFIANT(true, null, "pokemon"),
    DELTA_STREAM(true, null, "pokemon"),
    DESOLATE_LAND(true, null, "pokemon"),
    DISGUISE(true, null, "pokemon"),
    DOWNLOAD(true, null, "pokemon"),
    DRAGONS_MAW(true, null, "pokemon"),
    DRIZZLE(true, null, "pokemon"),
    DROUGHT(true, null, "pokemon"),
    DRY_SKIN(true, null, "pokemon"),
    EARLY_BIRD(true, null, "pokemon"),
    EARTH_EATER(true, null, "pokemon"),
    EFFECT_SPORE(true, null, "pokemon"),
    ELECTRIC_SURGE(true, null, "pokemon"),
    ELECTROMORPHOSIS(true, null, "pokemon"),
    EMERGENCY_EXIT(true, null, "pokemon"),
    FAIRY_AURA(true, null, "pokemon"),
    FILTER(true, null, "pokemon"),
    FLAME_BODY(true, null, "pokemon"),
    FLARE_BOOST(true, null, "pokemon"),
    FLASH_FIRE(true, null, "pokemon"),
    FLOWER_GIFT(true, null, "pokemon"),
    FLOWER_VEIL(true, null, "pokemon"),
    FLUFFY(true, null, "pokemon"),
    FORECAST(true, null, "pokemon"),
    FOREWARN(true, null, "pokemon"),
    FRIEND_GUARD(true, null, "pokemon"),
    FRISK(true, null, "pokemon"),
    FULL_METAL_BODY(true, null, "pokemon"),
    FUR_COAT(true, null, "pokemon"),
    GALE_WINGS(true, null, "pokemon"),
    GALVANIZE(true, null, "pokemon"),
    GLUTTONY(true, null, "pokemon"),
    GOOD_AS_GOLD(true, null, "pokemon"),
    GOOEY(true, null, "pokemon"),
    GORILLA_TACTICS(true, null, "pokemon"),
    GRASS_PELT(true, null, "pokemon"),
    GRASSY_SURGE(true, null, "pokemon"),
    GRIM_NEIGH(true, null, "pokemon"),
    GUARD_DOG(true, null, "pokemon"),
    GULP_MISSILE(true, null, "pokemon"),
    GUTS(true, null, "pokemon"),
    HADRON_ENGINE(true, null, "pokemon"),
    HARVEST(true, null, "pokemon"),
    HEALER(true, null, "pokemon"),
    HEATPROOF(true, null, "pokemon"),
    HEAVY_METAL(true, null, "pokemon"),
    HONEY_GATHER(true, null, "pokemon"),
    HUGE_POWER(true, null, "pokemon"),
    HUNGER_SWITCH(true, null, "pokemon"),
    HUSTLE(true, null, "pokemon"),
    HYDRATION(true, null, "pokemon"),
    HYPER_CUTTER(true, null, "pokemon"),
    ICE_BODY(true, null, "pokemon"),
    ICE_FACE(true, null, "pokemon"),
    ICE_SCALES(true, null, "pokemon"),
    ILLUMINATE(true, null, "pokemon"),
    ILLUSION(true, null, "pokemon"),
    IMMUNITY(true, null, "pokemon"),
    IMPOSTER(true, null, "pokemon"),
    INFILTRATOR(true, null, "pokemon"),
    INNARDS_OUT(true, null, "pokemon"),
    INNER_FOCUS(true, null, "pokemon"),
    INSOMNIA(true, null, "pokemon"),
    INTIMIDATE(true, null, "pokemon"),
    INTREPID_SWORD(true, null, "pokemon"),
    IRON_BARBS(true, null, "pokemon"),
    IRON_FIST(true, null, "pokemon"),
    JUSTIFIED(true, null, "pokemon"),
    KEEN_EYE(true, null, "pokemon"),
    KLUTZ(true, null, "pokemon"),
    LEAF_GUARD(true, null, "pokemon"),
    LEVITATE(true, null, "pokemon"),
    LIBERO(true, null, "pokemon"),
    LIGHT_METAL(true, null, "pokemon"),
    LIGHTNING_ROD(true, null, "pokemon"),
    LIMBER(true, null, "pokemon"),
    LINGERING_AROMA(true, null, "pokemon"),
    LIQUID_OOZE(true, null, "pokemon"),
    LIQUID_VOICE(true, null, "pokemon"),
    LONG_REACH(true, null, "pokemon"),
    MAGIC_BOUNCE(true, null, "pokemon"),
    MAGIC_GUARD(true, null, "pokemon"),
    MAGICIAN(true, null, "pokemon"),
    MAGMA_ARMOR(true, null, "pokemon"),
    MAGNET_PULL(true, null, "pokemon"),
    MARVEL_SCALE(true, null, "pokemon"),
    MEGA_LAUNCHER(true, null, "pokemon"),
    MERCILESS(true, null, "pokemon"),
    MIMICRY(true, null, "pokemon"),
    MINUS(true, null, "pokemon"),
    MIRROR_ARMOR(true, null, "pokemon"),
    MISTY_SURGE(true, null, "pokemon"),
    MOLD_BREAKER(true, null, "pokemon"),
    MOODY(true, null, "pokemon"),
    MOTOR_DRIVE(true, null, "pokemon"),
    MOXIE(true, null, "pokemon"),
    MULTISCALE(true, null, "pokemon"),
    MULTITYPE(true, null, "pokemon"),
    MUMMY(true, null, "pokemon"),
    MYCELIUM_MIGHT(true, null, "pokemon"),
    NATURAL_CURE(true, null, "pokemon"),
    NEUROFORCE(true, null, "pokemon"),
    NEUTRALIZING_GAS(true, null, "pokemon"),
    NO_GUARD(true, null, "pokemon"),
    NORMALIZE(true, null, "pokemon"),
    OBLIVIOUS(true, null, "pokemon"),
    OPPORTUNIST(true, null, "pokemon"),
    ORICHALCUM_PULSE(true, null, "pokemon"),
    OVERCOAT(true, null, "pokemon"),
    OVERGROW(true, null, "pokemon"),
    OWN_TEMPO(true, null, "pokemon"),
    PARENTAL_BOND(true, null, "pokemon"),
    PASTEL_VEIL(true, null, "pokemon"),
    PERISH_BODY(true, null, "pokemon"),
    PICKPOCKET(true, null, "pokemon"),
    PICKUP(true, null, "pokemon"),
    PIXILATE(true, null, "pokemon"),
    PLUS(true, null, "pokemon"),
    POISON_HEAL(true, null, "pokemon"),
    POISON_POINT(true, null, "pokemon"),
    POISON_TOUCH(true, null, "pokemon"),
    POWER_CONSTRUCT(true, null, "pokemon"),
    POWER_OF_ALCHEMY(true, null, "pokemon"),
    POWER_SPOT(true, null, "pokemon"),
    PRANKSTER(true, null, "pokemon"),
    PRESSURE(true, null, "pokemon"),
    PRIMORDIAL_SEA(true, null, "pokemon"),
    PRISM_ARMOR(true, null, "pokemon"),
    PROPELLER_TAIL(true, null, "pokemon"),
    PROTEAN(true, null, "pokemon"),
    PROTOSYNTHESIS(true, null, "pokemon"),
    PSYCHIC_SURGE(true, null, "pokemon"),
    PUNK_ROCK(true, null, "pokemon"),
    PURE_POWER(true, null, "pokemon"),
    PURIFYING_SALT(true, null, "pokemon"),
    QUARK_DRIVE(true, null, "pokemon"),
    QUEENLY_MAJESTY(true, null, "pokemon"),
    QUICK_DRAW(true, null, "pokemon"),
    QUICK_FEET(true, null, "pokemon"),
    RAIN_DISH(true, null, "pokemon"),
    RATTLED(true, null, "pokemon"),
    RECEIVER(true, null, "pokemon"),
    RECKLESS(true, null, "pokemon"),
    REFRIGERATE(true, null, "pokemon"),
    REGENERATOR(true, null, "pokemon"),
    RIPEN(true, null, "pokemon"),
    RIVALRY(true, null, "pokemon"),
    RKS_SYSTEM(true, null, "pokemon"),
    ROCK_HEAD(true, null, "pokemon"),
    ROCKY_PAYLOAD(true, null, "pokemon"),
    ROUGH_SKIN(true, null, "pokemon"),
    RUN_AWAY(true, null, "pokemon"),
    SAND_FORCE(true, null, "pokemon"),
    SAND_RUSH(true, null, "pokemon"),
    SAND_SPIT(true, null, "pokemon"),
    SAND_STREAM(true, null, "pokemon"),
    SAND_VEIL(true, null, "pokemon"),
    SAP_SIPPER(true, null, "pokemon"),
    SCHOOLING(true, null, "pokemon"),
    SCRAPPY(true, null, "pokemon"),
    SCREEN_CLEANER(true, null, "pokemon"),
    SEED_SOWER(true, null, "pokemon"),
    SERENE_GRACE(true, null, "pokemon"),
    SHADOW_SHIELD(true, null, "pokemon"),
    SHADOW_TAG(true, null, "pokemon"),
    SHARPNESS(true, null, "pokemon"),
    SHED_SKIN(true, null, "pokemon"),
    SHEER_FORCE(true, null, "pokemon"),
    SHELL_ARMOR(true, null, "pokemon"),
    SHIELD_DUST(true, null, "pokemon"),
    SHIELDS_DOWN(true, null, "pokemon"),
    SIMPLE(true, null, "pokemon"),
    SKILL_LINK(true, null, "pokemon"),
    SLOW_START(true, null, "pokemon"),
    SLUSH_RUSH(true, null, "pokemon"),
    SNIPER(true, null, "pokemon"),
    SNOW_CLOAK(true, null, "pokemon"),
    SNOW_WARNING(true, null, "pokemon"),
    SOLAR_POWER(true, null, "pokemon"),
    SOLID_ROCK(true, null, "pokemon"),
    SOUL_HEART(true, null, "pokemon"),
    SOUNDPROOF(true, null, "pokemon"),
    SPEED_BOOST(true, null, "pokemon"),
    STAKEOUT(true, null, "pokemon"),
    STALL(true, null, "pokemon"),
    STALWART(true, null, "pokemon"),
    STAMINA(true, null, "pokemon"),
    STANCE_CHANGE(true, null, "pokemon"),
    STATIC(true, null, "pokemon"),
    STEADFAST(true, null, "pokemon"),
    STEAM_ENGINE(true, null, "pokemon"),
    STEELWORKER(true, null, "pokemon"),
    STEELY_SPIRIT(true, null, "pokemon"),
    STENCH(true, null, "pokemon"),
    STICKY_HOLD(true, null, "pokemon"),
    STORM_DRAIN(true, null, "pokemon"),
    STRONG_JAW(true, null, "pokemon"),
    STURDY(true, null, "pokemon"),
    SUCTION_CUPS(true, null, "pokemon"),
    SUPER_LUCK(true, null, "pokemon"),
    SUPREME_OVERLORD(true, null, "pokemon"),
    SURGE_SURFER(true, null, "pokemon"),
    SWARM(true, null, "pokemon"),
    SWEET_VEIL(true, null, "pokemon"),
    SWIFT_SWIM(true, null, "pokemon"),
    SWORD_OF_RUIN(true, null, "pokemon"),
    SYMBIOSIS(true, null, "pokemon"),
    SYNCHRONIZE(true, null, "pokemon"),
    TABLETS_OF_RUIN(true, null, "pokemon"),
    TANGLED_FEET(true, null, "pokemon"),
    TANGLING_HAIR(true, null, "pokemon"),
    TECHNICIAN(true, null, "pokemon"),
    TELEPATHY(true, null, "pokemon"),
    TERAVOLT(true, null, "pokemon"),
    THERMAL_EXCHANGE(true, null, "pokemon"),
    THICK_FAT(true, null, "pokemon"),
    TINTED_LENS(true, null, "pokemon"),
    TORRENT(true, null, "pokemon"),
    TOUGH_CLAWS(true, null, "pokemon"),
    TOXIC_BOOST(true, null, "pokemon"),
    TOXIC_DEBRIS(true, null, "pokemon"),
    TRACE(true, null, "pokemon"),
    TRANSISTOR(true, null, "pokemon"),
    TRIAGE(true, null, "pokemon"),
    TRUANT(true, null, "pokemon"),
    TURBOBLAZE(true, null, "pokemon"),
    UNAWARE(true, null, "pokemon"),
    UNBURDEN(true, null, "pokemon"),
    UNNERVE(true, null, "pokemon"),
    UNSEEN_FIST(true, null, "pokemon"),
    VESSEL_OF_RUIN(true, null, "pokemon"),
    VICTORY_STAR(true, null, "pokemon"),
    VITAL_SPIRIT(true, null, "pokemon"),
    VOLT_ABSORB(true, null, "pokemon"),
    WANDERING_SPIRIT(true, null, "pokemon"),
    WATER_ABSORB(true, null, "pokemon"),
    WATER_BUBBLE(true, null, "pokemon"),
    WATER_COMPACTION(true, null, "pokemon"),
    WATER_VEIL(true, null, "pokemon"),
    WEAK_ARMOR(true, null, "pokemon"),
    WELL_BAKED_BODY(true, null, "pokemon"),
    WHITE_SMOKE(true, null, "pokemon"),
    WIMP_OUT(true, null, "pokemon"),
    WIND_POWER(true, null, "pokemon"),
    WIND_RIDER(true, null, "pokemon"),
    WONDER_GUARD(true, null, "pokemon"),
    WONDER_SKIN(true, null, "pokemon"),
    ZEN_MODE(true, null, "pokemon"),
    ZERO_TO_HERO(true, null, "pokemon"),
    HOSPITALITY(true, null, "pokemon"),
    MINDS_EYE(true, null, "pokemon"),
    EMBODY_ASPECT(true, null, "pokemon"),
    TOXIC_CHAIN(true, null, "pokemon"),
    SUPERSWEET_SYRUP(true, null, "pokemon"),
    TERA_SHIFT(true, null, "pokemon"),
    TERA_SHELL(true, null, "pokemon"),
    TERAFORM_ZERO(true, null, "pokemon"),
    POISON_PUPPETEER(true, null, "pokemon"),
    PIERCING_DRILL(true, null, "pokemon"),
    DRAGONIZE(true, null, "pokemon"),
    MEGA_SOL(true, null, "pokemon"),
    SPICY_SPRAY(true, null, "pokemon"),

    ADRENALINE(true, "Increases Speed when HP becomes half or less.", "sage"),
    ALLURE(true, "Lowers the evasiveness of foes of the opposite gender.", "sage"),
    BRAVE_HEART(true, "When opponent's stats are raised, Attack increases.", "sage"),
    CONDITIONING(true, "When a move is used in succession against the Pokémon, its damage is decreased.", "sage"),
    CONTENT(true, "The Pokémon regains HP each turn it does not attack.", "sage"),
    CONUNDRUM(true, "Contact with the Pokémon may confuse the attacker.", "sage"),
    DISCRETION("The Pokémon loses no PP following a miss.", "sage"),
    ECCENTRIC(true, "Boosts the Special Attack stat, but lowers accuracy.", "sage"),
    EVENTIDE("Ups Sp. Attack during the night and Defense during the day.", "sage"),
    FEEDBACK(true, "When a Pokémon with Feedback is hit by a non-contact physical or special move, the attacker loses 1/8th of its maximum HP. This damage occurs after each hit of multi-strike moves such as Icicle Spear.", "sage"),
    FEISTY(true, "Raises Attack if the foe's level is higher.", "sage"),
    FORAGE("The Pokemon may pick up berries.", "sage"),
    FULL_FORCE("Any move that the bearer uses which has a variable base power will always use the highest possible base power.", "sage"),
    ICE_SLICK(true, "Boosts the Pokémon's Speed in a hailstorm.", "sage"),
    IRON_JAW(true, "Boosts the power of biting moves.", "sage"),
    MALICE("The damage taken by an opponent from secondary damage (e.g. Life Orb, Spikes, weather, other end-of-round damage) is increased by 50%. This effect does not stack with itself.", "sage"),
    MOOCH("May consume the berries held by allies and foes.", "sage"),
    ORBITAL_TIDE(true, "While a Pokémon with Orbital Tide is in battle, the effect of the move Gravity is applied.", "sage"),
    OVERSHADOW("Lowers the Attack and Sp. Attack of shorter foes.", "sage"),
    PERFORATE(true, "The bearer's moves which are the same type as the bearer are not affected by the foe's type immunities (the move becomes 1x effective against the immune types).", "sage"),
    PERMAFROST(true, "Boosts the Pokémon's Defense in hail.", "sage"),
    PSYCH_OUT(true, "Lowers the foe's Special Attack stat.", "sage"),
    QUICKDRAW_SAGE("The priority of all moves of all Pokémon becomes 0. Detect, Endure, Protect, Quick Guard, and Wide Guard are unaffected.", "sage"),
    REACTIVE_SHIELDING("After a Pokémon with this Ability is hit by a move, Reactive Shielding increases its Defense or Special Defense by one stage (depending on the move's category), while the other defensive stat decreases by one stage.\n" +
            "If a Pokémon with this Ability is hit by a multi-strike move, each hit will activate this Ability. ", "sage"),
    SCAVENGER(true, "When the bearer knocks out a foe, the bearer recovers 25% of their maximum HP.", "sage"),
    SIPHON(true, "If a Pokémon with Siphon uses a move that makes contact, it will have a 30% chance to heal the bearer by half of the damage dealt, in addition to its normal effects. The amount of HP restored can be boosted by Big Root.", "sage"),
    SPECTRUM("Changes the primary type to match the foe's color.", "sage"),
    STUBBORN(true, "Increases the Pokemon's Defense when HP is halved.", "sage"),
    SUNBATHE(true, "The Pokémon gradually regains HP in sunlight.", "sage"),
    TEAM_PLAYER("The Pokémon and it's ally get increased boosts during double battles.", "sage"),

    //insurgence
    ABSOLUTION(
            true,
            "During intense darkness, Absolution increases the Pokémon's Special Attack by 50 percent, but the Pokémon loses 1/8 of its maximum HP at the end of each turn.",
            "insurgence"
    ),
    AMPLIFIER(
            true,
            "Amplifier boosts sound-based moves by 1.25×.",
            "insurgence"
    ),
    ANCIENT_PRESENCE("All damaging moves which follow the standard damage formula gain the same-type attack bonus even if the moves are not the same type as the user.\n" +
            "All damaging moves used by the wielder of Ancient Presence will always deal neutral damage, meaning all attacks ignore standard type-effectiveness relationships. Moves used under the effects of Ancient Presence still adhere to item or ability-based type-immunity such as Air Balloon or Levitate.\n" +
            "Ancient Presence overrides type effectiveness granted by the ability Omnitype. Pokémon with the ability Wonder Guard are completely immune to damaging attacks under the effects of Ancient Presence. ",
            "insurgence"),
    ATHENIAN(true,
            "Athenian doubles the Special Attack stat of the Pokémon with this Ability",
            "insurgence"
    ),
    BLAZE_BOOST("Immediately before the user uses a Fire-type attack its Attack, Special Attack, and Speed are increased by 1 stage. When Blaze Boost is activated by Delta Emolga, its form changes. When in this form, there is a 10% chance that Pokémon using a contact move against Delta Emolga will become burned.",
            "insurgence"),
    CASTLE_MOAT(true,"When a Pokémon with Castle Moat is hit by an Water-type move, its Special Defense is increased by one stage, and the move will have no effect on that Pokémon.", "insurgence"),
    CHLOROFURY("When a Pokémon with Chlorofury enters the battle, its Speed is raised by one stage and its Special Attack is raised by one stage for each fainted Pokémon on the user's team. After two turns, these stat changes are removed.", "insurgence"),
    ETHEREAL_SHROUD("Ethereal Shroud causes the user to gain Ghost-type-associated immunities and resistances, effectively giving them three defensive types in the event that the user already possesses a primary type and a secondary type. Ethereal Shroud does not give Ghost-type moves a damage increase via same-type attack bonus, and it also does not give the user weaknesses associated with its new Ghost typing.\n" +
            "Pokémon with the Abilities Scrappy, Mold Breaker, Teravolt, or Turboblaze are able to bypass Ethereal Shroud using Fighting-type and Normal-type moves. Using Foresight or Odor Sleuth also allows Fighting-type and Normal-type moves to bypass Ethereal Shroud. Trick-or-Treat and Forest's Curse will both fail when used against Pokémon with Ethereal Shroud. Soak, Dragonify, and Medusa Ray will not fail, however they also will not negate the Ghost-type-associated immunities and resistances gained from Ethereal Shroud. ", "insurgence"),
    EVENT_HORIZON(true,"Any Pokémon that makes contact with this one can't escape.", "insurgence"),
    FOUNDRY(true,"Foundry causes all Rock-type moves used by the Pokémon with this Ability to become Fire-type and receive a 30% damage boost, in addition to all other modifiers.\n" +
            "Furthermore, Foundry also causes Stealth Rock to become a Fire-type entry hazard that stacks with the normal, Rock-type Stealth Rock.", "insurgence"),
    GLITCH("Glitch has a 100% chance to instantly faint opposing Pokémon when hit by a contact move.", "insurgence"),
    HELIOPHOBIA(true,"During harsh sunlight, a Pokémon with Heliophobia will lose ⅛ of its maximum HP at the end of each turn. During intense darkness, a Pokémon with Heliophobia will regain ⅛ of its maximum HP at the end of each turn.", "insurgence"),
    HUBRIS(true,"When a Pokémon with Hubris causes another Pokémon (including allies) to faint through direct damage, its Special Attack rises by one stage. Hubris will not be activated by indirect damage, such as through Sandstorm or an item like Rocky Helmet. Hubris will not activate if an allied Pokémon defeats a foe in a Double or Triple Battle.", "insurgence"),
    ICE_CLEATS(true,"During hail, the Speed stat of Pokémon with this Ability is doubled. A Pokémon with this Ability will take no damage from hail if it otherwise would.", "insurgence"),
    INTOXICATE(true,"Intoxicate causes all Normal-type moves used by the Pokémon to become Poison-type and receive a 30% power boost.", "insurgence"),
    IRRELEPHANT(true,"Ignores type-based immunities.", "insurgence"),
    LERNEAN(true,"Pokémon with Lernean will gain more heads if their HP decreases below 80%, 60%, 40%, or 20%, gaining multiple heads if their HP falls below multiple of these thresholds at once. Restoring HP does not remove heads and more heads will not generate if a threshold has previously been reached. Lernean then splits the power of the user's damaging moves across each head.", "insurgence"),
    NOCTEM(true,"Noctem summons darkness in battle as soon as a Pokémon with Noctem enters the battle. Its effects are the same as the move New Moon.", "insurgence"),
    OMNI_TYPE(true,"All moves used against the target will factor in the weaknesses and resistances of every type at once, and grants the user type-based immunity effects.", "insurgence"),
    PENDULUM("Boosts the power of moves used repeatedly. Each time a move is used consecutively, " +
            "its power is boosted by 20% up to a maximum increase of 100%. Switching or using another move returns" +
            " the move's power to normal. Multi-strike moves are counted by the number of turns on which they are used, " +
            "not the number of hits made. It also stacks with Metronome, which offers an identical power boost for every consecutive usage.", "insurgence"),
    PERIODIC_ORBIT("When the moves Doom Desire, Future Sight, or Wish are used, they will activate twice after a single use. Wish will activate one and three turns after the move is originally used. Doom Desire and Future Sight will activate two and five turns after the move is originally used, and each will block further uses of Doom Desire or Future Sight until the second activation lands.", "insurgence"),
    PHOTOTROPH(true,"Pokémon with Phototroph restore 1/16 of their total HP at the end of each turn. The effects of Phototroph are doubled during harsh sunlight and are completely negated when the sky is dark or heavy rain is in effect.", "insurgence"),
    PRISM_GUARD(true,"When a Pokémon with Prism Guard is hit with an attack that does not make contact, the attacker takes damage equal to 1/8 of its own HP, after all turn-based damage is dealt. If Prism Guard causes both the user and the attacker to faint, then the attacker will faint first. It is the non-contact counterpart to Iron Barbs and Rough Skin.", "insurgence"),
    PROTEAN_MAXIMA("At the start of the turn, if directed to use a move of a type that corresponds to an Eeveelution, Mega Eevee will transform into the form corresponding to that Eeveelution, giving it the type, base stats (including HP) and ability of that Eeveelution. Using a Normal-type move changes Eevee back to its base Mega Evolution form. Protean Maxima is not replaced by the new ability; using a move of a different applicable type will cause Eevee to transform again.\n" +
            "When Mega Eevee transforms into a formAspects with a different base HP, its current HP will be revised to its new maximum HP minus the amount of HP it had lost before changing formAspects (unless that would put Eevee's HP at 0 or lower, in which case Eevee's HP is reduced to 1 instead). This also occurs when Mega Eevee transforms back into its non-Mega formAspects after a battle ends.", "insurgence"),
    PSYCHO_CALL(true,"Boosts Psychic-Type moves in a pinch.", "insurgence"),
    REGURGITATION("When a Pokémon with the Ability Regurgitation successfully using an attack or targetable status move, it will deal additional damage against the target. This damage is equal to 1/6 of the target's maximum HP multiplied by the effectiveness of the Regurgitation type against the target, which is determined by the primary typing of the Pokémon within Delta Muk's mouth. The type can be Water, Grass, Fire, Dark, Normal, or Psychic corresponding to Horsea, Bellsprout, Magby, Deino, Whismur, and Natu, respectively.", "insurgence"),
    SHADOW_CALL(true,"Boosts Dark-Type moves in a pinch.", "insurgence"),
    SHADOW_DANCE(true,"During intense darkness, the Speed stat of Pokémon with this Ability is doubled.", "insurgence"),
    SHADOW_SYNERGY(true,"Shadow Synergy boosts the power of the user's Dark-type moves by 50%.", "insurgence"),
    SLEET("Sleet summons and increases the damage of hail. Pokémon that are not immune to hail damage are damaged for 20% of their maximum HP at the end of each turn while Sleet is active. Sleet's effects are removed when Pokémon with Sleet are no longer on the field or hail stops. If hail stops but becomes active again while a Pokémon with Sleet is on the field, Sleet will immediately begin modifying the damage of hail.", "insurgence"),
    SPECTRAL_JAWS(true,"Spectral Jaws causes all biting moves used by the Pokémon to be reclassified as Special moves and receive a 30% boost.", "insurgence"),
    SPEED_SWAP("Speed Swap starts Trick Room in battle as soon as a Pokémon with Speed Swap enters the battle. If a Pokémon with Speed Swap enters the battle while Trick Room is already in effect, Trick Room will end immediately.", "insurgence"),
    SPIRIT_CALL(true,"Boosts Ghost-Type moves in a pinch.", "insurgence"),
    SUPERCELL("During intense darkness or rain, Supercell increases the Special Attack stat of the Pokémon with this Ability by 1.5×.\n" +
            "Supercell changes Delta Typhlosion from its Inactive Mode to Active Mode during darkness or rain.", "insurgence"),
    SYNTHETIC_ALLOY("Pokémon with Synthetic Alloy take neutral damage from Fire-type attacks regardless of their type-specific weaknesses.", "insurgence"),
    UNLEAFED("When a Pokémon with Unleafed enters the battle, its Attack, Defense, Special Attack, Special Defense, and Speed are increased by one stage each. These boosts last X + 1 turns, where X is the number of fainted Pokémon on this Pokémon´s team at the time of the ability's activation. After X + 1 turns, the stat changes are removed.", "insurgence"),
    VAMPIRIC(true,"Vampiric allows the user to regain 25% of the damage inflicted when using a contact move. The amount of HP recovered is unaffected by Big Root. If the effects of Heal Block are active, then Vampiric cannot restore HP.", "insurgence"),
    VAPORIZATION("Causes damage-dealing Water-type moves and targetable Water-type status moves to fail when used. Damages all Water-type Pokémon for ⅛ of their maximum HP at the end of every turn.", "insurgence"),
    VENOMOUS("A Pokémon with Venomous always causes bad poison instead of regular poison.", "insurgence"),
    WIND_FORCE(true,"When a Pokémon with Wind Force is hit by a Flying-type move, its Speed is increased by one stage, and the move will have no effect on that Pokémon. Wind Force will not activate if the Pokémon is protected from the Flying-type move.", "insurgence"),
    WINTER_JOY("During the months of November, December, January, and February, the Attack and Special Attack of Pokémon with this Ability are increased by 40%. During the months of May, June, July, and August the Attack and Special Attack of Pokémon with this ability are decreased by 30%. During the remaining four months, stats are unchanged.", "insurgence"),

    //infinity
    PURE_FOCUS("Raises the Pokémon's Special Attack stat.", "infinity"),

    //xenoverse
    CREAM_SHIELD("Lowers the damage taken from opposing Pokémon the healthier the user is.", "xenoverse"),
    CLOUD_BURST("Cloud Burst changes the ability-bearer's formAspects to 'Cloud Burst' when their health falls at or below 50%.", "xenoverse"),
    DREAD_SPACE("Makes the move of the foe, regardless if it's status/physical/special, use 2 PP instead of 1.", "xenoverse"),
    JUNGLE_SPIRIT(true, "Boosts the power of moves that are the same type as Shyleon. It is required to have it's hidden ability to use Shyleon's Astral formAspects.", "xenoverse"),
    MAJESTIC_AURA(true, "If an opponent uses a priority move that targets the Pokémon with Majestic Aura or its allies, Majestic Aura prevents the Pokémon from executing that move (PP is still consumed).", "xenoverse"),
    VOICE_TUNING(true, "Boosts the power of moves that are the same type as Trishout. It is required to have it's hidden ability to use Trishout's Astral formAspects.", "xenoverse"),
    DRAGON_ARMOR(true, "Boosts the power of moves that are the same type as Shulong. It is required to have it's hidden ability to use Shulong's Astral formAspects.", "xenoverse"),
    PIGGY_BANK("When the Pokémon has participated in a battle, prize money is doubled.", "xenoverse"),
    SYNTHESIZER("When the Pokémon is hit by a Sound-type move, its HP is restored by 1/4 of its maximum HP, and the move will have no effect on that Pokémon.", "xenoverse"),
    RAPTOR("Raptor gives priority when attacking a weak pokémon, which translates to gaining +1 priority when attacking a target with 25% hit points or less remaining.", "xenoverse"),
    DIRTY_POOL("When the Pokémon enters a battle or ends a turn with its HP above 25%, it changes from Solo Form to Monster Form. The formAspects will revert if the Pokémon's HP falls below 25%.", "xenoverse"),
    EQUALIZE("Turns Normal-type attacks into Sound-type moves and boosts their power", "xenoverse"),
    SCALATE("Normal-type moves become Dragon-type and boosts their power.", "xenoverse"),
    HOLY_GUARD("Holy Guard raises either the Defense stat or Special Defense stat by one stage depending on the foe's currently highest attack stat: it will raise Defense if the foe's current Attack is higher than its current Special Attack stat; otherwise, it will raise Special Defense.", "xenoverse"),
    MYSTIC_WIND("A pokémon with this ability will as the description state gain the resistances of the Fairy-type. This would make the pokémon more resistant to Bug, Fighting and Dark.", "xenoverse"),
    NULL_POINT("", "xenoverse"),
    SOLAR_PROMINENCE("It reduces the power of all attacks toward it by 33%, regardless of whether or not it's a contact move. ", "xenoverse"),


    //blazing emerald
    AIR_CONTROL(true, "The user's STAB moves are increased by 100% instead of 50% ", "blazing_emerald"),
    AMALGAM(true, "User changes type to the last move it used", "blazing_emerald"),
    AMBUSH(true, "User's moves cannot miss during an Eclipse", "blazing_emerald"),
    BARBED_NEST(true, "User takes half damage from contact moves and inflicts 1/8th Max HP recoil on the contacting Foe", "blazing_emerald"),
    CHARGED_WOOL(true, "User's Normal moves are now Electric type and deal 20% increased damage", "blazing_emerald"),
    COMPOSED(true, "Increases power of 2-turn moves by 50%", "blazing_emerald"),
    CRYSTAL_CASE(true, "Immune to Water and 1.5x weak to Fire. When hit by Fire move, sharply raises Special Attack (+2)", "blazing_emerald"),
    ELUSIVE(true, "Gives an extra 50% evasion to all status moves", "blazing_emerald"),
    EMPATHY(true, "Lower's foe's offenses when making contact with user", "blazing_emerald"),
    FOUL_SHROUD(true, "User's evasion is increased during an Eclipse", "blazing_emerald"),
    FRUITRITION(true, "Self recovery moves heal an extra 25%", "blazing_emerald"),
    GLACIALIZE(true, "User's Normal moves are now Ice type and deal 20% increased damage", "blazing_emerald"),
    INSATIABLE(true, "User's draining moves deal more damage", "blazing_emerald"),
    LASER_FOCUS(true, "Increases power of beam moves by 50%", "blazing_emerald"),
    LEVIN_SKIN(true, "Sharply raises Attack (+2) when hit by an Electric move", "blazing_emerald"),
    LITHE(true, "User's speed doubles when suffering from a status condition, ignores Paralysis speed drop", "blazing_emerald"),
    LUCKY_STAR(true, "Multiplies the accuracy of all the user's moves by 1.3x", "blazing_emerald"),
    NEFARIOUS(true, "User's status moves have +1 priority", "blazing_emerald"),
    POWER_FIST(true, "All punching moves increase in power by 20%", "blazing_emerald"),
    PROWLER(false, "Doubles the damage of any copied moves (Assist, Mirror Move, Mimic, etc.)", "blazing_emerald"),
    REGALIA(true, "User's Normal moves are now Fairy type and deal 20% increased damage", "blazing_emerald"),
    RESOLUTE(false, "At full health, user will survive an otherwise lethal blow with 1HP", "blazing_emerald"),
    SIEGE_DRIVE(true, "Increases power of projectile moves by 50%", "blazing_emerald"),
    SKY_SCOURGE(true, "Summons Eclipse on switch-in", "blazing_emerald"),
    SPECIALIST(false, "Increases power of HM moves by 50%", "blazing_emerald"),
    TACTICIAN(true, "User's not very effective moves deal double damage to foes", "blazing_emerald"),
    TENACIOUS(true, "Doubles user's Defense stat", "blazing_emerald"),
    VISIONARY(false, "User's Normal moves can now hit Ghost types", "blazing_emerald"),

    //solar light lunar dark
    AMPERATE(false, "Amperate causes all Normal-type moves used by the Pokémon to become Electric-type and receive a 30% power boost.", "solar_light_lunar_dark"),
    BLOODTHIRST(false, "The user's biting moves will also heal 1/8th of its total HP. Healing is negated if Heal Block is in play. The user takes damage if used on a target with Liquid Ooze. This does not count as an absorbing effect, so a Big Root will not boost it.", "solar_light_lunar_dark"),
    BOUNCY(false, "Inflicts damage equal to 1/3 HP lost by the user to the foe when attacked by a physical move. ", "solar_light_lunar_dark"),
    EQUILIBRIUM(false, "When a Pokémon with Equilibrium enters the battle, several conditions are removed. This includes stat changes, status ailments, weather effects, terrain effects, rooms (such as Trick Room), entry hazards, Mist, Light Screen, Reflect, Safeguard, and Lucky Chant.", "solar_light_lunar_dark"),
    FLAME_EATER(false, "When a Pokémon with Flame Eater is hit by a Fire-type move, its HP is restored by one quarter of its maximum HP, and the move will have no effect on that Pokémon (if a Pokémon with this Ability already has full HP, the Fire-type move will do nothing instead).\n" +
            "Flame Eater will not activate if the Pokémon is protected from the Fire-type move.", "solar_light_lunar_dark"),
    LUNAR_DIFFUSE(false, "When a Pokémon with Lunar Diffuse enters the battle, it creates the effect of the move Midnight Terrain on the battlefield.", "solar_light_lunar_dark"),
    REFRACTIVE(false, "Inflicts 1/8 HP damage to the attacker when attacked with non-contact moves.", "solar_light_lunar_dark"),
    SANDMAN(false, "When a Pokémon with this Ability is hit by a move that makes contact, there is a 30% chance that the attacking Pokémon will become asleep.\n" +
            "If a Pokémon with this Ability is hit by a multi-strike move that makes contact (such as Fury Swipes), each hit has an independent chance to activate this Ability.\n" +
            "Grass-type Pokémon, Pokémon with Overcoat, and Pokémon holding Safety Goggles are now immune to Sandman. ", "solar_light_lunar_dark"),
    SCARECROW(false, "The bearer is immune to any Flying-type moves.", "solar_light_lunar_dark"),
    SOLAR_DIFFUSE(false, "When a Pokémon with Solar Diffuse enters the battle, it creates the effect of the move Shining Terrain on the battlefield.", "solar_light_lunar_dark"),
    CROSS_GUARD(null, "solar_light_lunar_dark"),

    //uranium
    ACCELERATION(false, "Acceleration boosts the power of priority moves by 1.5x.", "uranium"),
    ATOMIZATE(false, "Normal-type moves become Nuclear-type moves and receive a 1.3x boost to base power.", "uranium"),
    BLOOD_LUST(true, "Blood Lust recovers some HP when attacking. It only activates if the attack lands, and activates every time a multi-strike move hits. The amount of HP healed is 1/6 of damage dealt.\n" +
            "The HP regained by Blood Lust is not affected by the Liquid Ooze ability.", "uranium"),
    CHERNOBYL(false, "Chernobyl creates a Nuclear Fallout for the duration of the Pokémon being in battle.", "uranium"),
    DEEP_FREEZE(false, "When a Pokémon with this Ability is hit by a move that makes contact, there is a 30% chance that the attacking Pokémon will become frozen.", "uranium"),
    DISENCHANT(false, "The bearer of Disenchant is completely immune to damage from Fairy type moves. It is currently unknown whether Pokémon with Disenchant are also immune to effects from non-damaging Fairy type moves.", "uranium"),
    ELEMENTALIST(false, "Elementalist is intended to treat Fire-, Water-, and Electric-type moves as if they were STAB, increasing the damage by 1.5x.", "uranium"),
    ENERGIZATE(false, "Normal-type moves become Electric-type moves and receive a 1.3x boost to base power.", "uranium"),
    GEIGER_SENSE(false, "Raises the bearer's Attack and Special Attack by one stage each when a Nuclear-type is in the field.", "uranium"),
    INFURIATE(false, "Infuriate raises Attack by one stage when the bearer is hit with a physical move.", "uranium"),
    LAZY(false, "Lazy causes the bearer to fall asleep as soon as they enter the field. Like Rest, the sleep effect only lasts two turns, albeit there is a chance it ends in the first or second turn.\n" +
            "The sleep from Lazy is normal otherwise. Snore and Sleep Talk can be used in its duration and it will prevent the bearer from being inflicted with other non volatile status conditions. The sleep from Lazy can also be cured with medication or held items and it will not be applied again so long as the bearer remains on the field.\n" +
            "If the bearer is inflicted with other status condition before switching in, Lazy will not activate and the bearer will remain awake.\n" +
            "Copying Lazy with Role Play or Trace, or transferring it with Skill Swap will not cause the target to fall asleep, as the ability only activates when the bearer enters the field. Similarly, negating it with Gastro Acid will not wake the bearer.\n" +
            "Similar to Truant, Lazy is a hindering ability.", "uranium"),
    LEAD_SKIN(false, "Gives full immunity to Nuclear type moves, with the exception of Nuclear Waste, which still badly poisons the target.", "uranium"),
    PETRIFY(false, "Petrify lowers the Speed stat of all opponents by one stage when the bearer enters the field. In a triple battle, Petrify can only lower the speed stat of opponents in range. It can be considered a Speed counterpart to Intimidate.", "uranium"),
    QUICK_CHARGE(false, "Quick Charge increases the priority of the first move used by the bearer by 4, during that turn only.\n" +
            "Quick Guard does not protect the user from Quick Charge-boosted moves since Quick Charge's priority is greater than Quick Guard's.\n" +
            "The boost in priority granted by Quick Charge stacks with other priority changes, making a Quick Charge-boosted Quick Attack +5 priority, and a hypothetical Quick Charge-boosted Roar -2 priority. ", "uranium"),
    REBUILD(false, "Heals 1/8 of the Pokemon's HP at the end of each turn if it was not hit by a direct attack. This ability is not interrupted by status effects like Burn or Poison as the heal is applied before status damage.", "uranium"),
    SHARP_CORAL(false, "Doubles Attack and Special Attack, but halves Defense and Special Defense.", "uranium"),
    SOUND_BOOST(false, "Sound-based moves get a 1.3x damage multiplier when used by a Pokémon with this ability. Does not neutralize the Soundproof ability.", "uranium"),
    STORMBRINGER(false, "Calls forth a Thunderstorm when the bearer is sent out, which lasts for five turns.", "uranium"),

    //Phoenix Rising
    MOMENTUM(false, "Each turn a move is used consecutively, its power is boosted by 20% up to a maximum increase of 100%. Switching Pokémon or using another move returns the move's power to normal.", "phoenix_rising"),

    //Lockemon
    ARCANUM(true, "Fills the area with the power of dragon force.", "lockemon"),
    CONDENSATION(true, "Fills the area with fog.", "lockemon"),
    DUST_DEVIL(true, "Creates a storm of earthy dust on the field.", "lockemon"),
    EVENTIDE_LOCKEMON(false, "Causes a blood moon to rise on the battlefield.", "lockemon"),
    FERROFLUX(true, "Creates a strong magnetosphere in the area.", "lockemon"),
    GALEFORCE(false, "Creates a strong air current through the area.", "lockemon"),
    HAY_FEVER(false, "Releases pollen into the air.", "lockemon"),
    INCANTATION(true, "Enchants the area with fairy dust.", "lockemon"),
    POLLUTION(false, "Fills the air with smog.", "lockemon"),
    SEANCE(true, "Creates a rift between this world and the next.", "lockemon"),
    SECRETION(false, "Fills the air with pheromones.", "lockemon"),
    STAND_OFF(true, "Focuses and projects their fighting spirit onto the battlefield.", "lockemon"),
    STORMFRONT(false, "Creates a thunderstorm.", "lockemon"),
    TRANSCENDENCE(true, "Creates a psychic field.", "lockemon"),
    ARENA_BLOOM(false, "Causes Spring pollen to coat the battlefield, in addition this Pokémon gradually regains HP in Pollen.", "lockemon"),
    ARENA_CURSE(false, "Causes an Autumn curse to coat the battlefield, in addition this Pokémon gradually steals HP from opponents in Cursed Winds.", "lockemon"),
    HEAT_HAZE(false, "This ability causes the first physical attack directed at Manadza to be reflected, dealing full damage to the attacker. After the attack is deflected, harsh sunlight begins. ", "lockemon"),
    ICE_ARMOR(false, "This ability causes the first special attack directed at Arctikull to be reflected, dealing full damage to the attacker. After the attack is deflected, hail begins.", "lockemon"),
    RELIC_SOUL(false, "Filled with the power of the Great Thunderbird, this Pokémon summons a thunderstorm upon entering battle. In addition, it receives full immunity to all Ground-type moves.", "lockemon"),
    ABSOLUTE_ZERO(false, "During a Hailstorm, this Pokémon's Ice-type attacks grow in power, doubling their chance to inflict their target with status.", "lockemon"),
    BLOOMSPRING(true, "The Pokémon gradually regains HP in Pollen.", "lockemon"),
    CARBON_CAPTURE(true, "The Pokémon gradually regains HP in Smog. In addition, this Pokémon becomes immune to the air's toxic effects.", "lockemon"),
    DRUIDRY(true, "The Pokémon gradually regains HP in Fairy Dust. In addition, this Pokémon possesses transmutative properties.", "lockemon"),
    ECLIPSE(false, "This Pokémon's Defense or Special Defense stats are raised sharply in a Blood Moon or Harsh Sunlight.", "lockemon"),
    ENERGIZER(true, "Boosts the Pokémon's Speed stat in a Thunderstorm.", "lockemon"),
    FORKED(true, "Heals status conditions in a Thunderstorm.", "lockemon"),
    GLACIAL_ARMOR(true, "Sharply boosts Defense and Special Defense in Hail.", "lockemon"),
    GRAVITY_SLING(false, "Boosts the Pokémon's Speed stat in magnetosphere.", "lockemon"),
    HAUNTING(false, "Boosts the Pokémon's Speed stat in a Cursed Winds or Blood Moon.", "lockemon"),
    MALICE_LOCKEMON(false, "Boosts the Sp.Atk stat in a Blood Moon, but decreases HP every turn.", "lockemon"),
    MASTER_INSTINCT(true, "Boosts the Pokémon's Accuracy in Battle Aura.", "lockemon"),
    NESTING(false, "The Pokémon gradually regains HP in Pheromones. If it has a Bug-type ally, the amount healed doubles.", "lockemon"),
    PETRICHOR(false, "While this Pokémon is active, Rain and Blood Moon both gain the effects of the other.", "lockemon"),
    POWER_ABOVE(false, "Boosts the power of Fairy, Grass-, Fire-, and Water-type moves in Fairy Dust.", "lockemon"),
    POWER_WITHIN(false, "Boosts the power of Dragon, Fire-, Electric-, and Ice-type moves in Dragon Force.", "lockemon"),
    SMOKE_AND_MIRRORS(false, "Boosts Special damage and increases the chance of confusing a target in a Psychic Field.", "lockemon"),
    SOUL_DRAIN(false, "The Pokémon gradually steals HP from opponents in Cursed Winds.", "lockemon"),
    WARP_MIST(true, "This Pokémon can no longer have its type immunities bypassed. Additionally, this Pokémon gains 1.2x attack power in Fog.", "lockemon"),
    WET_AND_DRY(false, "This Pokémon changes formAspects depending on how wet or dry the weather is.", "lockemon"),

    ANCIENT_BODY(true, "This Pokemon is considered Rock-type, in addition to its other types.", "lockemon"),
    BUBBLE_HELM(false, "Immune to irritant weathergy.", "lockemon"),
    CHAKRA(false, "Powers up Fairy-type moves.", "lockemon"),
    DROUGHTPROOF(false, "Immune to climate weathergy.", "lockemon"),
    ECHOLOCATION(false, "Sound-based moves strike twice.", "lockemon"),
    ENJOIN(false, "Enhances moves that command others.", "lockemon"),
    EVERGREEN(false, "Allows Snover and Abomasnow to switch between their Lowland and Highland forms.", "lockemon"),
    EXPIATION(false, "After fainting, the Pokemon that switches into the user's position will be healed.", "lockemon"),
    FIELDWORKER(false, "Multiplies the base power of Grass-type moves by 1.5x.", "lockemon"),
    FLYTRAP(false, "The user's sticky jaws become very effective at trapping Bug-type Pokémon.", "lockemon"),
    FOIL(false, "The steadfast mind of this Pokémon halves the damage from Psychic-type moves that hit it.", "lockemon"),
    FRIGID_BLAZE(false, "This Pokémon's Ice-type moves have a chance to burn. As well, its Fire-type moves have a chance to frostbite.", "lockemon"),
    GEIGER_AURA(false, "Reduces the HP of adjacent Pokémon.", "lockemon"),
    HYDROPHOBIC(false, "Immune to the effects of rain and hail, and halves Water-type damage.", "lockemon"),
    //intoxicate
    NASTY_WEBBING(false, "Scatters sticky webs at the feet of the opposing team when this Pokémon takes damage from physical moves.", "lockemon"),
    NEUTRALIZE(false, "When the user drops below half HP, all abilities are nullified and weathers are cleared. ", "lockemon"),
    NOT_TO_BE(false, "Any attacker that faints this Pokémon will also perish. ", "lockemon"),
    NULLIFY(false, "Nullifies all weathergies and prevents any from being set up while this Pokémon is on the field.", "lockemon"),
    PEARL_DROP(false, "Drops pearls on the ground when sent out, making it harder to land attacks.", "lockemon"),
    ROCKY_BODY(false, "Once per battle, the unstable rocks atop this Pokémon will protect from an attack before scattering themselves.", "lockemon"),
    ROOT_CONTROL(false, "The user lays roots that restore its HP on every turn. Even though it's rooted, it can still switch out.", "lockemon"),
    //smother body
    SONGBIRD(false, "While this Pokémon is on the field, its allies will only take damage from attacks.", "lockemon"),
    SOUL_PASSAGE(false, "Upon switching in after the Pokemon in its position fainted, the user gains the highest statistical increase of that Pokemon.", "lockemon"),
    SURVEILLANCE(false, "Increases the user's accuracy.", "lockemon"),
    SWARMING(false, "Forms a powerful swarm while it has a lot of HP. Pheromones causes this swarm to become permanent.", "lockemon"),
    TO_BE(false, "This Pokémon cannot be knocked out with one hit. Upon reaching 1 HP, it will regain some of its health.", "lockemon"),
    TRUMPET_WEEVIL(false, "The user's sound-based moves become Bug-type and they gain a 1.5x boost.", "lockemon"),
    VEGETATE(false, "Normal-type moves become Grass-type moves. The power of those moves is boosted a little.", "lockemon"),
    TWO_FACED(null, "lockemon"),

    //vanguard
    AVIAN(false, "STAB to Flying atks, immunity to wind moves.", "vanguard"),
    BLAZE_IMPACT(false, "May burn the target on contact.", "vanguard"),
    DARKENED_SCALES(false, "Halves damage taken from physical moves.", "vanguard"),
    MALEVOLENCE(false, "Dark-type moves gain priority when its HP is full.", "vanguard"),
    MINDTUNING(false, "Boosts its best stat in Psychic Terrain.", "vanguard"),
    REVIVAL_SHEDDING(false, "Changes formAspects when HP falls below half.", "vanguard"),
    SAND_SHROUD(false, "The Pokemon gradually regains HP in a sand- or dust-storm", "vanguard"),
    POWER_DRAIN(false, "Draining moves have increased healing.", "vanguard"),
    ARTIFICER(false, "Recoil moves increase the user's Speed stat upon use.", "vanguard"),
    APEX_NEIGH(false, "Increases Def and SpDef when user defeats an opponent", "vanguard"),
    DUALITY(false, "Moves that hit twice have double power.", "vanguard"),
    HYPERVANITYM(false, "The user's Atk/Def is raised/lowered by 1 when it switches in.", "vanguard"),
    HYPERVANITYF(false, "The user's Sp.Atk/Sp.Def is raised/lowered by 1 when it switches in.", "vanguard"),
    MIRROR_SPELL(false, "Inflicts damage upon being hit by a Special attack.", "vanguard"),
    SOUL_CONDUCTOR(false, "Moves that affect the soul are stronger.", "vanguard"),
    TIDAL_NEIGH(false, "Increases Defense when user defeats an opponent.", "vanguard"),
    WARPING_NEIGH(false, "Increases Special Defense when user defeats an opponent.", "vanguard"),
    SONGSTRESS(false, "Negates and powers up its own Sound-Type moves if hit by one.", "vanguard"),
    FLAME_TOUCH(false, "May burn targets when the PokÃ©mon makes contact.", "vanguard"),
    GOLDEN_HARVEST(false, "Heals teammate in double battles", "vanguard"),
    PARASOMNIA(false, "Sleeping enemies have their health sapped. Accuracy of sleep moves increased.", "vanguard"),
    SNOWBALL(false, "Moves that lock the user into attacking are 1.3x power and increase defenses.", "vanguard"),
    MELTING_POINT(false, "Changes form when hit by fire type or burn-inducing move.", "vanguard"),
    AVARICE_VANGUARD(false, "The user steals the opponent's item upon entering battle. The user can't steal if it is already holding an item.", "vanguard"),
    AVARICE(false, "The user steals the opponent's item upon entering battle. The user can't steal if it is already holding an item.", "vanguard"),
    SPIKY_SHEDDING("Scatters spikes upon contact.", "vanguard"),
    CREMATION(null, "vanguard"),
    WITHERING_OFFER("Boosts every stat after knocking out an ally.", "vanguard"),
    VACUUM_CORE("Increases SpAtk when hit by Electric and wind-based moves. Electric moves are drawn in.", "vanguard"),
    WIND_MAESTRO("Avoids ally's attacks. Wind moves boost Attack.", "vanguard"),

    //daybreak
    CRYO_SHELL(false, "Cryo Shell restores 1⁄16 (6.25%) of the bearer's HP at the end of each turn during rain or Hail. It can be seen as a combination of Rain Dish and Ice Body", "daybreak"),
    MAXIMUM(false, "Maximum increases the user's Special Attack stat by 1 stage upon knocking out an opponent and changes the user's typing to that of the move it is currently using. The user gains STAB from all of its moves as a result. ", "daybreak"),
    PRIMALITY(false, "Removes the effects of Weather Conditions (but not the weather itself) and randomly raises Special Attack, Special Defense or Speed by 2 stages at the end of every turn", "daybreak"),

    //flux
    SERENE_VEIL(false, "Protects the Pokémon and its ally from the additional effects of attacks taken.", "flux"),
    BOMBARDIER(false, "Powers up ball and bomb moves.", "flux"),
    CRYSTALLIZE(false, "Normal-type moves become Rock-type moves. The power of those moves is boosted a little.", "flux"),
    TERRA_FIRMA(false, "Extends the duration of terrains created by the Pokémon or its ally.", "flux"),
    RUGGED_ARMOR(false, "Halves recoil damage and the damage taken from moves that make direct contact, but halves the Pokémon's Speed stat.", "flux"),
    SLEIGHT_OF_HAND(false, "If the Pokémon uses a move that swaps or takes away a held item, it can use it even if the target protects itself.", "flux"),
    POWER_THIEF(false, "Stat-lowering effects that the Pokémon inflicts raise its own stats.", "flux"),
    BOILINGPOINT(false, "The Pokémon is angered when it takes a critical hit, and that maxes its Sp. Atk stat.", "flux"),
    OBSIDIAN_BODY(false, "The Pokémon's obsidian body damages the target slightly when it makes contact.", "flux"),
    WIND_PROPULSION(false, "Boosts the Speed stat drastically when the Pokémon is hit by a wind move.", "flux"),
    ALPHA_WOLF(false, "5% boost in damage for every ally that is neither fainted nor has a status condition, including itself, for a maximum of 30%.", "flux"),
    ARCHETYPAL(false, "Applies a 1.2x boost to moves of the user's types for both the user and its ally. Stacks with itself if both a user and its ally have Archetypal.", "flux"),
    CLAIRVOYANCE(false, "This Pokemon can hit Dark-types with Psychic-type moves.", "flux"),
    DEFIBRILLATOR(false, "If this Pokémon is a Nursa at full HP, after an ally faints, it stays on the field and is immediately restored to 1 HP. This Pokémon then loses 1/8 of its max HP. If the Pokémon is restored to max HP, it can be activated again. This ability cannot be Traced or gained by Role Play, replaced by Worry Seed or Simple Beam, exchanged with Skill Swap or given to another Pokémon by Entrainment.", "flux"),
    SATELLITE(false, "This Pokemon makes its move immediately before its ally if its ally's move is the same priority. If the user and an opponent are in a Speed tie, the Pokémon with Satellite will move before both opponent and ally no matter which way the Speed tie resolves.", "flux"),
    TOXIC_SURGE(false, "On switch-in, this Pokemon summons Toxic Terrain.", "flux"),

    //opal
    ASTONISHMENT(null, "opal"),
    INFLAMABLE(null, "opal"),
    STEALTH_WINGED(null, "opal"),

    //foret eternelle
    STRENGTHENING(null, "eternal_forest"),

    //umbra
    FINISHER(false, "Finisher pumps up the user when they get a Pokémon to 1/2 health or less granting +2 to their Attack and Special Attack until their next damaging move. (Can use status boosts on self without wasting the Finisher.)", "umbra"),
    PREDATOR(false, "Predator heals the user by 1/4th of their max HP when defeating an opponent with a contact move. ", "umbra"),
    SCORCHING_SURGE(false, "Scorching Surge will change the terrain on the field to Scorched Terrain (unknown terrain).", "umbra"),
    SENSORY_BOOST(false, "Sensory Boost increases the accuracy of moves used by the Pokémon with this ability by 10%.", "umbra"),
    SIDE_EFFECT(false, "Side Effect adds confusion to any status effect inflicted on a target by the user. This includes status effects caused by attacking moves like Scald.", "umbra"),
    VAMPIRISM(false, "Vampirism heals the user by 1/4th of the damage dealt with biting moves.", "umbra"),
    WOLF_S_TRAP(false, "Wolf's Trap prevents Dragon, Flying, Grass, Ground, Ghost, and Psychic Pokémon from switching or fleeing from battle.", "umbra"),

    //gravels extended battles
    BOLD_AS_BRASS(true, "Boosts the power of the user's sound type and sound based moves by 50%, at the cost of increasing damage taken from them. Reduces fire type damage by 50%", "geb"),
    BOREAL_INSTINCT(true, "if the target is frostbitten and the user is an ice type, boosts Biting moves power by 50%", "geb"),
    CIRCUS_PROPS(true, "Sets up Trick Room when user switches in", "geb"),
    CLIMATE_CHANGE(true, "Summons a random weather, grants immunity to damaging weathers", "geb"),
    COPPER_STATE(true, "Water type moves do double damage to the user, water based weather hurts the user, electric type moves hit the user, thunderstorm heals the user", "geb"),
    COSMIC_PRESENCE(true, "Sets up gravity when user switches in", "geb"),
    COVER_ME_IN_DEBRIS(true, "Grants the user immunity to fire type moves and the burned status condition", "geb"),
    DIGITIZE(true, "Normal Type moves become Digital Type", "geb"),
    ENERGY_SHIELD(true, "The User is not affected by beam and laser moves", "geb"),
    ESCAPE_VELOCITY(true, "Under the effects of gravity, doubles the speed stat", "geb"),
    FOOL_S_GOLD(true, "Boosts the user's critical hit ratio but lowers its accuracy on switch in", "geb"),
    FOSSILIZE(true, "Normal Type moves become Rock Type", "geb"),
    FROM_BEGINNING_TO_END(true, "Boosts the user's critical hit ratio for slicing and fire type moves but makes it unnable to use status moves", "geb"),
    FROST_HEAL(true, "Heals 1/8th HP at the end of the turn if the user is frostbitten", "geb"),
    GUTTER_MIND(true, "Psychic Type moves become Poison Type", "geb"),
    INVIGORATE(true, "Normal Type moves become Fighting Type", "geb"),
    IRON_WILL(true, "Prevents the user from flinching and having its stats lowered", "geb"),
    MAGICIAN_S_HAT(true, "Sets up Magic Room when user switches in", "geb"),
    PRISMATIC_HUE(true, "Sets up Reflect on the user's side", "geb"),
    RAD_SIPPER(true, "if the user is hit by a Nuclear type move it boosts Special attack by one stage, during fallout the user heals 1/16th HP", "geb"),
    RHYTHM_GAME(true, "Boosts the power of moves used consecutively by 20% up to 100%, boosts reset if the user switches move", "geb"),
    RIDER_SYNDROME(true, "Boosts kicking moves when the user's HP is below 30%", "geb"),
    SILVER_LINING(true, "The user's steel type moves hit Ghost and Dark types super effectively", "geb"),
    SNOWY_SURGE(true, "Sets up Snowy Terrain on switch in", "geb"),
    TERRORIZE(true, "Normal Type moves become Ghost Type", "geb"),
    UNSTABLE(true, "Changes the pokemon's type to match that of moves used against it, as well as the moves it uses", "geb"),
    VIBRANT_HUE(true, "Sets up Light Screen on the user's side", "geb"),
    WIZARD_S_TOME(true, "Sets up Wonder Room when user switches in", "geb"),
    XENOFORCE(true, "Under the effects of gravity, the pokemon's attack is increased", "geb"),
//    BRUTALIZE(true),
//    BUSY_BEE(true),
//    CONFIDENT(true),
//    HEADACHE(true),
//    NATURAL_TOXIN(true),
//    ROSES_THORNS(true),
//    WIND_TURBINE(true),

    SNOWPLOW(null, "pokengine"),
    SCAVENGE(false, "The Pokémon scavenges the battlefield after knocking out any Pokémon, restoring a little HP.", "pokengine"),
    ADHESIVE(false, "Contact with the Pokémon may trap the attacker.", "pokengine"),
    DELICIOUS(false, "Infatuates the attacker when hit by a biting move.", "pokengine"),
    SUGAR_COAT(false, "The attacker gets covered with sugar on contact. The sugar coat makes all its attacks become Fairy-type.", "pokengine"),
    ARCANE_OVERLOAD(false, "Boosts the Pokémon's most proficient stat every time it's hit with a move that matches its own type.", "pokengine"),
    SHARPSHOOTER(false, "Boosts the accuracy of some ball and bomb moves.", "pokengine"),
    NIGHT_STALKER(false, "The Pokémon's physical attacks are boosted at night. Its Dark-type attacks have an increased chance of landing a critical hit.", "pokengine"),
    FIREPROOF(false, "Sharply boosts its Defense stat if hit by a Fire-type move, instead of taking damage.", "pokengine"),
    SWIFT_DODGE(false, "The Pokémon evades any status moves and traps set on the field when entering a battle.", "pokengine"),
    SOUL_ABSORB(false, "If hit by a Ghost-type move, the Pokémon has its HP restored instead of taking damage.", "pokengine"),
    SUNSCREEN(false, "Prevents the Pokémon from getting a burn. It will also gradually regain HP in sunshine.", "pokengine"),
    HAY_HIDE(false, "Halves the damage taken from moves that make direct contact, but doubles that of Fire-type moves.", "pokengine"),
    GREEN_THUMB(false, "Draws in all Grass-type moves. Instead of being hit by Grass-type moves, it boosts its Sp. Atk stat.", "pokengine"),
    MOUNTAINEER(false, "With its skill in mountainous terrain, this Pokémon evades all Rock-type moves and hazards.", "pokengine"),
    UNDERLING(false, "Powers up the Pokémon's physical attacks when battling with an ally that has a higher Attack stat than itself.", "pokengine"),
    FEROCIOUS(false, "Frightens opposing Pokémon and makes them unable to raise their Attack or Sp. Atk stats.", "pokengine"),
    DARK_HOLD(false, "Draws in all Dark-type moves. Instead of being hit by Dark-type moves, it boosts its Defense stat.", "pokengine"),
    NOCTURNAL(false, "The Pokémon gradually regains HP at night or during Dark Overcast. The damage taken from Dark-type moves is also halved.", "pokengine"),
    RUBBER_BODY(false, "The Pokémon receives full immunity to all Electric-type moves, which bounce off its rubber skin.", "pokengine"),
    JACKPOT(false, "Boosts a random stat after landing a critical hit. The prize money received after battle is also increased.", "pokengine"),
    ACID_CLOUD(false, "Summons Acid Rain that damages all Pokémon except the Poison-type.", "pokengine"),
    PERPLEXING(false, "Contact with the Pokémon may confuse the attacker.", "pokengine"),
    SECRET_INSIGHT(false, "The Pokémon relies on its mystical power to navigate. Its Sp. Atk stat is boosted, but accuracy is lowered.", "pokengine"),
    DREAMER(false, "The Pokémon's sweet dreams restore a little HP every turn it is asleep.", "pokengine"),
    REFLEX_STRIKE(false, "This Pokémon retaliates automatically, dealing a small amount of damage to the attacker on contact.", "pokengine"),
    RAZOR_FINS(false, "Powers up moves that make direct contact.", "pokengine"),
    POWER_LEECH(false, "Powers up draining moves.", "pokengine"),
    GOLD_RUSH(false, "Draws in all Rock- and Steel-type moves. Instead of being hit by Rock- and Steel-type moves, it boosts its Defense stat.", "pokengine"),
    REEL_IN(false, "Prevents Water-type Pokémon from escaping.", "pokengine"),
    FIERY_SPIRIT(false, "", "pokengine"),
    FRACTURE(false, "The Pokémon's attacks become critical hits if the target is burned.", "pokengine"),
    PINWHEEL(false, "Being hit by a Flying-type move boosts the Speed stat of the Pokémon.", "pokengine"),
    SECOND_WIND(false, "The Pokémon whips up a tailwind when it takes a hit that causes its HP to become half or less.", "pokengine"),
    SUPERCHARGE(false, "Powers up Electric-type moves when the Pokémon's HP is low.", "pokengine"),
    INFESTED_DRIVE(false, "Powers up Bug-type moves.", "pokengine"),
    SWARMING_SURGE(false, "Turns the ground into Swarming Terrain when the Pokémon enters a battle.", "pokengine"),
    TIGHT_GRIP(false, "Extends the duration of the Pokémon's binding moves.", "pokengine"),
    CALCULATE(false, "Compares an opposing Pokémon's Attack and Sp. Atk stats before raising its own Defense or Sp. Def stat—whichever will be more effective.", "pokengine"),
    TOPPINGS(false, "Holding a Berry boosts the Pokémon's stats. Which stat is boosted depends on the Berry's flavor.", "pokengine"),
    IGNITION(false, "Being hit by a Fire-type move boosts the Speed stat of the Pokémon.", "pokengine"),
    ROUGHHOUSER(false, "Powers up tackling moves. The Pokémon also takes recoil damage from these kinds of moves.", "pokengine"),
    BODYGUARD(false, "The Pokémon's body shields its allies from a single attack when they enter battle.", "pokengine"),
    POWER_LIFTER(false, "The Pokémon's attacks deal more damage to heavier targets.", "pokengine"),
    COMBAT_SKIN(false, "Its combat skin blocks the additional effects of attacks taken. It also reduces damage taken from contact moves.", "pokengine"),
    PYROTOXIN(false, "Powers up Fire-type moves if the target is poisoned, and powers up Poison-type moves if the target is burned.", "pokengine"),
    JAWBREAKER(false, "Harshly lowers the Attack stat of the attacker when hit by a biting move.", "pokengine"),
    AIRBORNE(false, "This Pokémon is always airborne, avoiding all ground-based moves and effects. It also can't be grounded.", "pokengine"),
    PERCEIVE(false, "Removes and prevents any field effects except for weather. It prevents the use of Transform and Illusion as well.", "pokengine"),
    ILL_WILL(false, "Opposing Pokémon that are poisoned have a random stat reduced each turn.", "pokengine"),
    BREAK_QUARANTINE(false, "This Pokémon's toxins are released when it faints from a direct attack, poisoning all Pokémon on the battlefield.", "pokengine"),
    RELENTLESS(false, "When the Pokémon knocks out a target, it strengthens its pursuit, boosting its Speed stat.", "pokengine"),
    SHADY_DEALINGS(false, "When the Pokémon enters a battle, it switches its held item with the target's.", "pokengine"),
    PATHOGENIC(false, "Contact with the Pokémon changes the attacker's Ability to Pathogenic. Pokémon with this Ability that are not Poison-type are hurt a little each turn.", "pokengine"),
    FILTHY_SURGE(false, "Turns the ground into Filthy Terrain when the Pokémon enters a battle.", "pokengine"),
    DUAL_SKIN(false, "The Pokémon takes less damage from \"not very effective\" moves and more damage from supereffective moves.", "pokengine"),
    CLONAL_COPY(false, "The Pokémon self-replicates each turn to boost all its stats at once.", "pokengine"),
    INVIGORATE_POKENGINE(false, "Normal-type moves become Fighting-type moves. The power of those moves is boosted a little.", "pokengine"),
    TRAMPLE(false, "This Pokémon's trampling feet destroy any traps and terrain effects on the field when entering a battle.", "pokengine"),
    TANTRUM(false, "The Pokémon throws a tantrum when it takes a critical hit, and that maxes its Sp. Atk stat.", "pokengine"),
    TEARY_EYED(false, null, "pokengine"),
    CONTROLLED_BURN(false, "If the Pokémon takes damage from a Fire-type move while its stats have changed, it sheds the burned outer layer, reducing the damage taken and removing its stat changes.", "pokengine"),
    DRONING_NOISE(false, "Torments all other Pokémon on the field, making them have to go for a different move each turn.", "pokengine"),
    OUTBURST(false, "Powers up Dragon-type moves when the Pokémon's HP is low.", "pokengine"),
    OVERCHARGED(false, "Gives priority to an Electric-type move used on the first turn this Pokémon is in battle.", "pokengine"),
    OVERWHELMING(false, "The Pokémon's attacks always land, but PP usage is raised.", "pokengine"),
    JUMP_IN(false, "The Pokémon's two-turn moves happen at once.", "pokengine"),
    STEAM_POWER(false, "The power of the Pokémon's Water-type moves are boosted in sunshine, instead of being weakened.", "pokengine"),
    HERBALIST(false, "The Pokémon may create another Herb after one is used.", "pokengine"),
    STONECUTTER(false, "The Pokémon may create another Gem after one is used.", "pokengine"),
    SPIRIT_BOUND(false, "Prevents Ghost-type Pokémon from escaping.", "pokengine"),
    EXPLOITATIVE(false, "Powers up moves that are supereffective.", "pokengine"),
    TASTE_BUDS(false, "When the Pokémon eats, it shares the effects of the held item with its allies.", "pokengine"),
    TIME_TWIST(false, "When its HP becomes half or less, the Pokémon twists the dimensions to invert speed order for three turns.", "pokengine"),
    TIDAL_SHIFT(false, "When the Pokémon uses Surf or Dive, it changes to its Sea Form. It changes back to its Land Form if it uses Surf or Dive again.", "pokengine"),
    MELT_COVER(false, "The Pokémon changes to its Blazing Form in sunny weather, or when hit by a Fire-type move. It reverts to its Frozen Form in any other weather, or when hit by an Ice- or Water-type move.", "pokengine"),
    STORM_STREAM(false, "Draws in all wind moves. Instead of being hit by wind moves, it boosts its Sp. Atk.", "pokengine"),
    CONTAMINATE(false, "Normal-type moves become Poison-type moves. The power of those moves is boosted a little.", "pokengine"),
    LUNAR_PHASE(false, "The Pokémon changes form, depending on how much HP it has left.", "pokengine"),
    PLOT_TWIST(false, "If hit by a Fairy-type move, the Pokémon has its HP restored instead of taking damage.", "pokengine"),
    BANANA_SPLIT(false, "The Pokémon's Grass-type attacks hit twice.", "pokengine"),
    PRIDEFUL_STANCE(false, "Its physical attacks are boosted when battling against a Pokémon that has a type advantage.", "pokengine"),
    REALITY_WARP(false, "Inverts type matchups of incoming attacks.", "pokengine"),
    NUTRIENT_RUNOFF(false, "When an opposing Pokémon uses a healing move, the Pokémon steals half of what would be healed.", "pokengine"),
    FINALE(false, "Powers up Fighting-type moves when the Pokémon's HP is low.", "pokengine"),
    COURAGEOUS(false, "Halves any damage taken when the Pokémon enters a battle.", "pokengine"),
    PARASITIC(false, "Steals the stat boosts of a target when the Pokémon makes contact.", "pokengine"),
    ROMANTIC(false, "Its romantic aura makes it attractive even to Pokémon of the same gender.", "pokengine"),
    FLIER(false, "The Pokémon takes direct damage as if it was Flying-type.", "pokengine"),
    NURTURER(false, "Cures an incoming ally's status when switching out.", "pokengine"),
    TRAFFIC_JAM(false, "While the Pokémon is in the battle, other Pokémon entering the battle have their Speed stats lowered.", "pokengine"),
    TEMPER(false, "Powers up Steel-type moves when the Pokémon's HP is low.", "pokengine"),
    SNOOZE(false, "The Pokémon may occasionally fall asleep during a battle to rest and recover its HP.", "pokengine"),
    OPEN_SEA(false, "The Pokémon's Water-type moves hit everything around it.", "pokengine"),
    PECKING_ORDER(false, "Boosts the power of the Pokémon's Flying-type moves, and lowers the power of everyone else's.", "pokengine"),
    LAST_STAND(false, "The Pokémon's Attack and Defense stats are boosted when it is the last Pokémon available.", "pokengine"),
    WHITE_VIRTUE(false, "This Pokémon radiates a bright mystical aura. Fairy-type moves are powered up while Dark-type moves are weakened.", "pokengine"),
    GLIMMER(false, "Powers up Fairy-type moves when the Pokémon's HP is low.", "pokengine"),
    SUDDEN_SEED(false, null, "pokengine"),
    BLACK_VICE(false, "This Pokémon is shrouded in an obscure dark aura. Dark-type moves are powered up while Fairy-type moves are weakened.", "pokengine"),
    SUPERPOSITION(false, "\tAt the end of each turn, the Pokémon teleports out of battle.", "pokengine"),
    SAND_BATH(false, "Restores the Pokémon's HP in sandstorm or when it is hit by Ground-type moves. Reduces HP in heavy rain, and increases the damage received from Water-type moves.", "pokengine"),
    HEAT_RUSH(false, "Boosts the Pokémon's Speed stat in harsh sunlight.", "pokengine"),
    DOUBLE_TAP(false, "The user's attacks that share its type hit twice, with the second attack being slightly weaker.", "pokengine"),
    OPEN_MAW(false, "The Pokémon changes its form to Ravenous Forme when it uses Ambuscade and changes to Patient Form when it uses an attack move.", "pokengine"),
    THERMAL_POWER(false, null, "pokengine"),
    BLAST(false, null, "pokengine"),
    ENTER_SPHERE(false, null, "pokengine"),
    ALLURING_GLOW(false, null, "pokengine"),
    SIGNAL_BOOST(false, null, "pokengine"),
    ALL_SEEING(false, null, "pokengine"),
    DESERT_BODY(false, null, "pokengine"),
    BULLY(false, null, "pokengine"),
    ILL_INTENT(false, null, "pokengine"),
    STATIC_TOUCH(false, null, "pokengine"),
    LAST_BASTION(false, null, "pokengine"),
    ROARING_HORN(false, null, "pokengine"),
    UNSTABLE_POKENGINE(false, null, "pokengine"),
    REVERB(false, null, "pokengine"),
    VINDICTIVE(false, null, "pokengine"),
    LIGHT_GUARD(false, null, "pokengine"),
    LIQUID_CONDUCTION(false, null, "pokengine"),
    MADNESS(false, null, "pokengine"),
    LIFEBLOOD(false, null, "pokengine"),
    VERMILINGUA(false, null, "pokengine"),
    ROOTED(false, null, "pokengine"),
    UNHOLY(false, null, "pokengine"),
    REFLECTIVE(false, null, "pokengine"),
    FREESTYLE(false, null, "pokengine"),
    TRICKSTER(false, null, "pokengine"),
    WONDERHARP(false, null, "pokengine"),
    WINDUP(false, null, "pokengine"),
    FERTILE_GIFTS(false, null, "pokengine"),
    HUMIDIFY(false, null, "pokengine"),
    SCORCHING_COAT(false, null, "pokengine"),
    LIGHT_DRAIN(false, null, "pokengine"),
    SUPERNOVA(false, null, "pokengine"),
    ROUND_RECORD(false, null, "pokengine"),
    RAIN_BOON(false, null, "pokengine"),
    SOOTHING_SHINE(false, null, "pokengine"),
    FLUORESCENCE(false, null, "pokengine"),
    BERRY_PLUMAGE(false, null, "pokengine"),
    MAGMATIC_HEAT(false, null, "pokengine"),
    PROXY(false, null, "pokengine"),
    RAPID_STREAM(false, null, "pokengine"),
    HEAVY_EYED(false, null, "pokengine"),
    IAI_SLASH(false, null, "pokengine"),
    SAVED_UP_POWER(false, null, "pokengine"),
    DYNAMIC_POWER(false, null, "pokengine"),
    CRYSTAL_SURGE(false, null, "pokengine"),
    SPICE_TANK(false, null, "pokengine"),
    ROCKY_TRAP(false, null, "pokengine"),
    SOUNDWAVES(false, null, "pokengine"),
    MASTER_THIEF(false, null, "pokengine"),
    WEATHER_BENEFIT(false, null, "pokengine"),
    DEFENSE_BOOST(false, null, "pokengine"),
    ABYSSAL_ARMOR(false, null, "pokengine"),
    DEVIATE(false, "Normal-type moves become Dark-type moves. The power of those moves is boosted a little.", "pokengine"),
    PRISMATIC_POWER(false, null, "pokengine"),
    EVAPORATION(false, "The Pokémon's heat evaporates Water-type attacks before they make contact, creating a shield of steam that raises the Sp. Def stat.", "pokengine"),
    WARM_HANDS(false, null, "pokengine"),
    ACCLIMATIZE(false, "The Pokémon's form changes to match the current terrain.", "pokengine"),
    ROCKFALL(false, "Powers up Rock-type moves when the Pokémon's HP is low.", "pokengine"),
    UPDRAFT(false, "Powers up Flying-type moves when the Pokémon's HP is low.", "pokengine"),
    DREAM_TRAP(false, "The Pokémon's looming presence prevents sleeping Pokémon from fleeing.", "pokengine"),
    COLD_STORAGE(false, "The Pokémon’s frozen rations will fully restore its HP when its HP drops to half or less, but the attack also changes the Pokémon’s appearance.", "pokengine"),
    BRANCH_OUT(false, "The Pokémon's Grass-type moves hit all opposing Pokémon.", "pokengine"),
    BUG_GLUTTON("The user's biting moves are boosted, and, if hit by a Bug-type move, the user has its HP restored instead of taking damage.", "pokengine"),

    //africanus
//    OJOS_PETREOES(),
//    PIEL_PUNICA(),
    OJOSPETREOS(null, "africanus"),

    //soulstones
    CHARISMA("On KO, SpAtk is boosted once per switch-in.", "soulstones"),
    LIGHT_BULB("Weakens incoming Dark moves, 2x Light moves. User's Light-type moves deal 2x damage. User takes 0.5x damage from Dark-type moves.", "soulstones"),
    POUNCE("On switch-in, user gains priority for first move.", "soulstones"),
    LEADERSHIP("On switch-in, user gains priority for first move.", "soulstones"),
    LIGHT_AURA("Powers up each Pokemon's Light-type moves. When user is on the field, all PokÃ©mon on both sides deal 1.33x damage with Light-type moves.", "soulstones"),
    IMPENETRABLE("Prevents other Pokemon from lowering Def/SpDef.\n" +
            "User's Defense and Special Defense stats cannot be lowered by other PokÃ©mon.", "soulstones"),
    SYNTHESIZE("The PokÃ©mon regains 1/8 max HP in sunlight.", "soulstones"),
    PACKED_SNOW("Halves effectiveness of S/E moves in Hail.\n" +
            "User takes 0.5x damage from super effective moves during Hail. User takes no damage from Hail.", "soulstones"),
    DISHEARTEN("Lowers the foe's Sp. Atk stat.\n" +
            "Lowers all adjacent foes' Special Attack stat by one stage when user enters the field.", "soulstones"),
    ANTI_GRAVITY("Sound/Ground can hit Cosmic. User's Sound and Ground-type moves deal 1x damage against Cosmic types.", "soulstones"),
    CANNON_FIRE("Powers up bomb-type moves.\n" +
            "User's moves with the bomb flag deal 1.5x damage.", "soulstones"),
    VITALITY("Raises the PokÃ©mon's Sp.Def when hit.", "soulstones"),
    INTUITION("Prevents other PokÃ©mon from lowering Sp. Atk stat.\n" +
            "User's Special Attack stat cannot be lowered by other PokÃ©mon.", "soulstones"),
    ATTUNEMENT("Boosts Sp. Atk if there is a status problem.\n" +
            "User gets 1.5x Special Attack when under any status condition.", "soulstones"),
    NEBULA_CLOUD("Protects Cosmic-types from stat/status effects.\n" +
            "When user is on the field, all Cosmic-type allies including the user become immune to stat drops inflicted from other PokÃ©mon, as well as non-volatile status effects.", "soulstones"),
    STARSTRUCK("Powers up Cosmic-type moves in a pinch.\n" +
            "User's Cosmic-type moves deal 1.5x damage when they have 1/3 or less HP remaining.", "soulstones"),
    REQUIEM("Powers up Dark-type moves.\n" +
            "User's Dark-type moves deal 1.5x damage. Stacks multiplicatively with STAB.", "vanguard"),
    MAESTRO("Powers up Sound-type moves in a pinch.\n" +
            "User's Sound-type moves deal 1.5x damage when they have 1/3 or less HP remaining.", "vanguard"),
    IRRADIATE("Powers up Light-type moves in a pinch.\n" +
            "User's Light-type moves deal 1.5x damage when they have 1/3 or less HP remaining.", "soulstones"),
    PURE_HEART("Gradually regains 1/16 max HP each turn.", "soulstones"),
    FORTIFICATION("Ups Def and Sp. Def if a hit makes its HP <50%.", "soulstones"),
    UNBREAKABLE("Prevents other PokÃ©mon from lowering Defense.\n" +
            "User's Defense stat cannot be lowered by other PokÃ©mon.", "soulstones"),
    TERRORIZE_SOULSTONES("Weakens incoming Bug moves, 2x Psychic moves\n" +
            "User's Psychic-type moves deal 2x damage. User takes 0.5x damage from Bug-type moves.", "soulstones"),
    OPAQUENESS("Immune to Light-type moves.", "soulstones"),
    ASTRAL_MAJESTY("Halves damage from Light and Dragon-type moves.", "soulstones"),
    DISARRAY("Temporarily twists the dimensions.\n" +
            "User sets up Trick Room when entering the field.", "soulstones"),
    GENIUS("Doubles the PokÃ©mon's Sp. Atk stat.", "soulstones"),
    LEECHING_FANGS("Restores 1/8 life with every biting contact move.", "soulstones"),
    TROPICAL_HIDE("Halves damage from Grass and Water-type moves.", "soulstones"),
    CONDUCTOR("Electric moves can hit Ground or Electric.\n" +
            "User's Electric-type moves deal 1x damage against Ground or Electric types.", "soulstones"),
    BLACKLIGHT("Light moves become 1.2x power Dark moves.\n" +
            "User's Light-type moves become Dark-type and deal 1.2x damage.", "soulstones"),
    ICY_VEINS("Ups Ice and Water moves in hail.\n" +
            "User's Ice and Water-type moves deal 1.3x damage during Hail. User takes no damage from Hail.", "soulstones"),
    VIRTUOSO("Powers up Sound-type moves.\n" +
            "User's Sound-type moves deal 1.5x damage. Stacks multiplicatively with STAB.", "soulstones"),
    AFFECTION("Powers up Fairy-type moves.\n" +
            "User's Fairy-type moves deal 1.5x damage. Stacks multiplicatively with STAB.", "soulstones"),
    REALISM("Halves damage from Ghost and Fairy-type moves.", "soulstones"),
    CLAY_FORM("The PokÃ©mon regains 1/8 max HP in a sandstorm.\n" +
            "The PokÃ©mon regains 1/8 max HP every turn during a Sandstorm. User takes no damage from Sandstorm.", "soulstones"),
    VENGEFUL("Ups Atk and Speed if a hit makes its HP <50%.", "soulstones"),
    NOBILITY("Makes foes unable to use priority attacks.", "soulstones"),
    SCORCH_SCALE("Burns any attacker that uses priority moves on it.", "soulstones"),
    HIVE_BODY("Contact moves apply Infestation.\n" +
            "When user is hit by a move that makes contact, there's a 30% chance to trap the attacker in Infestation.", "soulstones"),
    IRREDEEMABLE("Halves damage from Light and Fairy-type moves.", "soulstones"),
    PRECISION("The PokÃ©mon's accuracy is boosted.\n" +
            "User's moves have 1.3x Accuracy.", "soulstones"),
    SPELLCASTER("Powers up Psychic-type moves in a pinch.\n" +
            "User's Psychic-type moves deal 1.5x damage when they have 1/3 or less HP remaining.", "soulstones"),
    DARK_MATTER("Normal moves become 1.2x power Cosmic moves.\n" +
            "User's Normal-type moves become Cosmic-type and deal 1.2x damage.", "soulstones"),
    TORMENTED("Boosts the Sp.Atk stat but lowers accuracy.\n" +
            "User has 1.5x Special Attack but 0.8x Accuracy with special moves.", "soulstones"),
    WHITEOUT("Dark moves become 1.2x power Light moves\n" +
            "User's Dark-type moves become Light-type and deal 1.2x damage.", "soulstones"),
    HIVEMIND("Powers up Bug-type moves.\n" +
            "User's Bug-type moves deal 1.5x damage. Stacks multiplicatively with STAB.", "soulstones"),
    ETHEREAL("Shields the PokÃ©mon from one contact move.", "soulstones"),
    BONE_COLLECTOR("Powers up Ground-type moves.\n" +
            "User's Ground-type moves deal 1.5x damage. Stacks multiplicatively with STAB.", "soulstones"),
    TERMINATOR("Ups Atk if a hit makes its HP <50%.", "soulstones"),
    WINTER_GIFT("Powers up party's SpAtk/SpDef in hail.\n" +
            "When user is on the field, all allies including user get 1.5x Special Attack and Special Defense during Hail. User takes no damage from Hail.", "soulstones"),
    HAUNTED("Powers up Ghost-type moves.\n" +
            "User's Ghost-type moves deal 1.5x damage. Stacks multiplicatively with STAB.", "soulstones"),
    COMET_STORM("+1 Speed/SpAtk when hit by a Rock-type move\n" +
            "User takes no damage from Rock-type moves, when hit by a Rock-type move their Special Attack and Speed is increased by one stage.", "soulstones"),
    MAELSTROM("Traps grounded foes. Contact engulfs them in a whirlpool.\n" +
            "When user is on the field, adjacent grounded enemies cannot escape or switch out. When user is hit by a move that makes contact, there's a 30% chance to trap the attacker in a Whirlpool.", "soulstones"),
    ARSONIST("Powers up Fire-type moves.\n" +
            "User's Fire-type moves deal 1.5x damage. Stacks multiplicatively with STAB.", "soulstones"),
    TV_FACE("Prevent a physical attack. Restored in electric terrain.\n" +
            "Protects from one physical attack, entering electric terrain will restore this shield. Form and stats change when the shield is down.", "soulstones"),
    REGROWTH(" Regains 1/16 max HP or lowered stats each turn.\n" +
            "All of user's lowered stats are restored by 1 stage at the end of each turn, if user has no lowered stats regain 1/16 max HP at the end of each turn instead.", "soulstones"),
    REAPER("Fainting foes in trainer battles heal you for 20%.", "soulstones"),
    DESTRUCTIVE_CORE("It explodes if its HP becomes half or less.\n" +
            "When HP is reduced to 50% or less, user changes to Reactive Form. This form has reduced defenses but increased Attack and Speed.", "soulstones"),
    SYMPHONY("Forms a symphony while it has > 25% HP and at Level 20+.", "soulstones"),
    DARK_SWARM("Forms a dark swarm while it has > 25% HP and at Level 20+.", "soulstones"),

    //forman
    ACTIVE(null, "form"),
    FIGHTBACK(null, "form"),
    XRAY(null, "form"),
    HEALINGENTRANCE(null, "form"),
    RAGINGSCALE(null, "form"),
    MELTDOWN(null, "form"),
    UNSTABLELAYERS(null, "form"),
    PLUCKING(null, "form"),
    LASTDUST(null, "form"),
    GLACIERS(null, "form"),
    BURNINGENTRANCE(null, "form"),
    ABSOLUTEFREEZE(null, "form"),
    SEAWALK(null, "form"),
    GRAVITYENTRANCE(null, "form"),
    LASTCHANCE(null, "form"),
    BALANCEENTRANCE(null, "form"),
    ELECTRICJAW(null, "form"),
    WITHERING(null, "form"),
    BLESSINGAIR(null, "form"),
    CHARGING(null, "form"),
    CURSEDAIR(null, "form"),
    MOISTMIST(null, "form"),
    ROUGHDIAMOND(null, "form"),
    ARTBLOCK(null, "form"),
    FIGHTERACT(null, "form"),
    DRAGONDUST(null, "form"),
    INESCAPABLE(null, "form"),
    SACREDDANCE(null, "form"),
    ENERGYJAIL(null, "form"),
    TOXICCLAWS(null, "form"),

    //el dark core
    BURNTMODE(null, "el_dark_core"),
    STATIC_TOXIC(null, "el_dark_core"),
    UNBOUND_TORRENT(null, "el_dark_core"),
    FAIRPLAY(null, "el_dark_core"),
    UNBIND(null, "el_dark_core"),
    BALANCE(null, "el_dark_core"),
    ICYBODY(null, "el_dark_core"),
    UNNARVE(null, "el_dark_core"),
    TARGETBLOCK(null, "el_dark_core"),
    LOSTCONTROL(null, "el_dark_core"),
    GUIDESOUND(null, "el_dark_core"),
    UNBOUNDRECKLESS(null, "el_dark_core"),
    UNDERZERO(null, "el_dark_core"),
    SOUNDREFLECT(null, "el_dark_core"),
    GLOW(null, "el_dark_core"),
    UNBOUNDREGENERATOR(null, "el_dark_core"),
    TOTALREFLECTION(null, "el_dark_core"),
    UNBOUNDOVERGROW(null, "el_dark_core"),
    UNBOUNDSTATIC(null, "el_dark_core"),
    FEARNESS(null, "el_dark_core"),
    TWINWING(null, "el_dark_core"),
    UNBOUNDBLAZE(null, "el_dark_core"),
    HARTKEY(null, "el_dark_core"),
    LIFESTRING(null, "el_dark_core"),
    VENOMOUSTOUCH(null, "el_dark_core"),
    DOOMED(null, "el_dark_core"),
    HYPE(null, "el_dark_core"),
    NEXTABSORBING(null, "el_dark_core"),
    UNBOUNDMARVELSCALE(null, "el_dark_core"),
    GIVINGENERGY(null, "el_dark_core"),
    ATOVERGROW(null, "el_dark_core"),
    ATTORRENT(null, "el_dark_core"),
    ATBLAZE(null, "el_dark_core"),
    GREED(null, "el_dark_core"),
    ELECTRIZE(null, "el_dark_core"),
    KEENEYES(null, "el_dark_core"),
    UNBOUNDNORMALIZE(null, "el_dark_core"),
    SOUNDABSORB(null, "el_dark_core"),
    THICKFUR(null, "el_dark_core"),
    MULTIPLY(null, "el_dark_core"),
    UNBOUNDICYBODY(null, "el_dark_core"),
    STEELBUILT(null, "el_dark_core"),
    EXTREMETOXIC(null, "el_dark_core"),
    GHOSTTOUCH(null, "el_dark_core"),
    BIGPEAKS(null, "el_dark_core"),
    TOTALBALANCE(null, "el_dark_core"),
    UNBOUNDIRONFIST(null, "el_dark_core"),
    RAGINGAIR(null, "el_dark_core"),
    UNBOUNDSWARM(null, "el_dark_core"),
    DOUBLEHEAD(null, "el_dark_core"),
    UNBOUNDTOUGHCLAWS(null, "el_dark_core"),
    SOILFLIPPING(null, "el_dark_core"),
    ABSORBCHAOS(null, "el_dark_core"),
    MUDSPLASH(null, "el_dark_core"),
    WATERVOICE(null, "el_dark_core"),
    CHANGINGORDER(null, "el_dark_core"),
    SOILFEEDING(null, "el_dark_core"),
    CHAOS(null, "el_dark_core"),
    ENERGYDEVOUR(null, "el_dark_core"),
    NOISY(null, "el_dark_core"),
    EXTRASPEED(null, "el_dark_core"),
    GLOWING(null, "el_dark_core"),
    TOTALABSORBTION(null, "el_dark_core"),
    SIGNALMAKER(null, "el_dark_core"),
    UNBOUNDPIXILATE(null, "el_dark_core"),
    UNBOUNDPOISONTOUCH(null, "el_dark_core"),
    UNBOUNDSANDFORCE(null, "el_dark_core"),
    TOXICLEFTOVER(null, "el_dark_core"),
    ROYALBLOOD(null, "el_dark_core"),
    THETRUTH(null, "el_dark_core"),
    RAGEQUIT(null, "el_dark_core"),
    DECEIVER(null, "el_dark_core"),
    POSSESSION(null, "el_dark_core"),
    UNBOUNDTINTEDLENS(null, "el_dark_core"),
    BURNINGTREE(null, "el_dark_core"),
    LEAKINGTREE(null, "el_dark_core"),
    UNBOUNDSTAKEOUT(null, "el_dark_core"),

    //artworks218
    WIZARDSSPELL(null, "artworks218"),
    ROYALORDER(null, "artworks218"),
    ROCKYSPIRIT(null, "artworks218"),
    WITCHESBREWING(null, "artworks218"),

    //kuulkid
    STRONG_START("Protects the Pokémon from supereffective attacks on its first turn in battle.", "pokengine"),
    FRUGAL("When the Pokémon enters a battle, it switches its held item with the opponent if the opponent's item is more valuable.", "pokengine"),
    MATERNAL("The Pokémon's Attack stat is boosted if an ally in the party is an Egg.", "pokengine"),
    TRASH_GUARD("The Pokémon takes no damage when hit by Poison-type moves. Instead, its Defense stat is sharply boosted.", "pokengine"),
    WELL_TRAINED("The Pokémon takes neutral damage from Fighting-type attacks.", "pokengine"),
    MELTY("In harsh sunlight, the Pokémon's Defense stat is lowered but its Speed stat is boosted.", "pokengine"),
    PANIC_SHIELD("Evades supereffective moves when the Pokémon's HP is low.", "pokengine"),
    HEADLESS("Boosts the Pokémon's Speed stat if it is confused.", "pokengine"),
    DOUBLE_DRAGON("Boosts the power of Dragon-type moves but makes them consume more PP.", "pokengine"),
    RADICAL_MUTAGEN("Changes all adjacent Pokémon's types to a randomly selected type.", "pokengine"),
    FORETELL("The Pokémon foretells the outcome of the fight, boosting one of its stats to aid in battle.", "pokengine"),
    SLIP_N_SLIDE("The Pokémon's Water-type moves are followed by a bonus Fighting-type attack and vice-versa.", "pokengine"),
    VERSATILE_BODY("The Pokémon gains a third type if it has a status condition.", "pokengine"),
    COLD_BLANKET("Cures the Pokémon's status conditions during snowfall.", "pokengine"),
    CONFLAGRATE("Normal-type moves become Fire-type moves. The power of those moves is boosted a little.", "pokengine"),
    SPLASH_FROLIC("The Pokémon recovers HP whenever Mud Sport or Water Sport are used in battle.", "pokengine"),
    CALMING_AURA("Contact with this Pokémon may cause sleep.", "pokengine"),
    GOURMAND("The Pokémon's HP is restored when it eats any Local Specialty.", "pokengine"),
    MUNCH_MISSILE("When the Pokémon uses Dig or Bulldoze, it will come back with prey. When it takes damage, it will spit out the prey to attack.", "pokengine"),
    COUNTING_SHEEP("Pokémon stay asleep for longer when this Pokémon is active.", "pokengine"),
    NIGHTGUARD("Reduces damage dealt to sleeping allies.", "pokengine"),
    SOPRANO("The Pokémon's sound-based moves hit all adjacent Pokémon.", "pokengine"),
    PARTY_ANIMAL("Doubles the effects of stat changes this Pokémon gains from performing dance moves.", "pokengine"),
    SNOW_FORT("The Pokémon's Defense and Sp. Def stats are boosted when hit with an Ice-type move.", "pokengine"),
    SIZZLING("Powers up Fire-type moves.", "pokengine"),
    MATING_CALL("The Pokémon's Attack stat is boosted for every other Pokémon of the opposite gender in battle.", "pokengine"),
    HIBERNATE("The Pokémon enters its Cryosleep forme when frozen or put to sleep.", "pokengine"),
    DYING_MEMORY("When the Pokémon enters a battle, its type changes to the type of the ally in the party that was most recently defeated.", "pokengine"),
    TAKEOVER("When the Pokémon knocks out a target, it steals the target's Ability.", "pokengine"),
    TALK_BACK("Whenever a sound move is used in battle by an opposing Pokémon, the Pokémon will copy the user to immediately perform that sound move itself.", "pokengine"),
    TERRAFORM("Powers up Ground-type moves when the Pokémon's HP is low.", "pokengine"),
    COLD_BLOODED("Restores the Pokémon's HP in harsh sunlight or when it is hit by Fire-type moves. Reduces HP in snow, and increases the damage received from Ice-type moves.", "pokengine"),
    BACKUP_THREAD("Protects the Pokémon from low priority moves.", "pokengine"),
    FRENZY("If the Pokémon misses the opponent because of accuracy, its Attack stat will be boosted sharply in a frenzy.", "pokengine"),
    GLITCHED("When hit by a move, the Pokémon's type will change randomly and one of the Pokémon's stats will be boosted sharply but another stat will be lowered.", "pokengine"),
    DARK_MIGHT("Boosts the power of Ghost- and Dark-type moves in a dark overcast.", "pokengine"),
    HEXPELLER("If hit by a Ghost-type move, the Pokémon retaliates, dealing damage instead of taking it.", "pokengine"),
    BURIED_HEAD("Head protection prevents flinching, being confused, recoil damage or being affected by Intimidate. When hit by an attack, the Pokémon loses its head protection and becomes aggressive.", "pokengine"),
    STREAMLINE("The Pokémon's streamlined body halves the damage taken by Water- and Flying-type moves.", "pokengine"),
    DRENCH("Changes the attacker's type to Water when the Pokémon is knocked out.", "pokengine"),
    BOX_FORT("The Pokémon's Defense stat is boosted while asleep.", "pokengine"),
    RED_HOT("The Pokémon's Steel-type moves have a chance to burn.", "pokengine"),
    HIGHRISE("The Pokémon's Ground-type moves can hit Flying-types.", "pokengine"),
    FOUL_MOUTH("The Pokémon's sound-based moves have a chance to taunt the opponent.", "pokengine"),
    SUGAR_CRASH("The Pokémon's Fairy-type moves are boosted, but lower the Pokémon's Defense and Sp. Def stats.", "pokengine"),
    COVEN("The Pokémon's Sp. Atk stat is boosted for every other Dark-type Pokémon in battle.", "pokengine"),
    DIVERSION("Opponents sometimes target this Pokémon instead of their original target.", "pokengine"),
    METALLIZE("Normal-type moves become Steel-type moves. The power of those moves is boosted a little.", "pokengine"),
    SUNSHROUD("The Pokémon summons a dark overcast when it enters a battle.", "pokengine"),
    SINISTER_SURGE("Turns the ground into Sinister Terrain when the Pokémon enters a battle.", "pokengine"),
    FALSE_FLIER("The Pokémon takes direct damage as if it was Flying-type.", "pokengine"),

    //fra
    BLAZE_VORTEX(null, "fra"),
    FALSE_FIRE("The Pokémon takes direct damage as if it was Fire-type.", "pokengine"),
    SMOKE_OUT(null, "solar_light_lunar_dark"),
    FOUNTAINING(null, "solar_light_lunar_dark");

    private String name;
    private boolean implemented;
    private String description;
    private String game;
    private boolean incomplete;

    Ability(
            @Nullable String description,
            String gameNamespace
    ){
        this.name = name().toLowerCase().replaceAll("_", "");
        this.implemented = false;
        this.description = description;
        this.game = gameNamespace;
        this.incomplete = description == null;
    }

    Ability(
            boolean implemented,
            String description,
            String gameNamespace
    ){
        this(description, gameNamespace);
        this.implemented = implemented;
    }

    public Boolean isImplemented() {
        return implemented;
    }

    public String getName() {
        if(isImplemented()) return name;
        return KEEN_EYE.name;
    }

    public static int getLastIndexOfOfficialAbility(){
        return Arrays.stream(Ability.values()).toList().indexOf(SPICY_SPRAY);
    }

    public String getDescription() {
        return description;
    }

    public String getGame() {
        return game;
    }

    public boolean isIncomplete() {
        return incomplete;
    }

    public AbilityIdentifier getIdentifier(){
        var gameNamespace = game == null ? "pokemon" : game;
        return new AbilityIdentifier(gameNamespace, getName());
    }
    
    public record AbilityIdentifier(String game, String name) implements JsonSerializable {
        @Override
        public JsonElement toJson() {
            var json = new JsonObject();
            json.addProperty("game", game);
            json.addProperty("name", name);
            return json;
        }

        public boolean is(AbilityIdentifier other) {
            return game.equalsIgnoreCase(other.game) && name.equalsIgnoreCase(other.name);
        }
    }
}
