modLoader="kotlinforforge"
loaderVersion="[5.10,)"
#issueTrackerURL = "A valid URL to your issue tracker where people can open bug tickets"
license = "MIT License"
[[mixins]]
config = "gravels_extended_battles_neoforge.mixins.json"
[[mixins]]
config = "gravels_extended_battles_common.mixins.json"
[[mods]]
modId = "gravels_extended_battles"
version = "${version}"
displayName = "Cobblemon Multiplatform-NeoForge Template Sidemod"
authors = "Me!"
description = '''
A very cool multi-line description!
'''
#logoFile = ""

[[dependencies.gravels_extended_battles]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.gravels_extended_battles]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1.182,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.gravels_extended_battles]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.7.3,)"
ordering = "AFTER"
side = "BOTH"
